In [2]:
import pandas as pd
import numpy as np

In [82]:
l = pd.read_excel('./원장/Socket/계정별원장(2021).xlsx')

#자료
l_2018 = pd.read_excel('./원장/Socket/계정별원장(2018).xlsx', sheet_name = None)
l_2019 = pd.read_excel('./원장/Socket/계정별원장(2019).xlsx', sheet_name = None)
l_2020 = pd.read_excel('./원장/Socket/계정별원장(2020).xlsx', sheet_name = None)
l_2021 = pd.read_excel('./원장/Socket/계정별원장(2021).xlsx', sheet_name = None)

l

,Unnamed: 0,Unnamed: 1,Unnamed: 2,계 정 별 원 장,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,2021.01.01 ~ 2021.12.31,NaN,NaN,NaN
1,회사명:(주)위너에코텍,NaN,NaN,NaN,NaN,NaN,계정과목 : [103] 보통예금
2,날짜,적 요 란,코드,거래처,차 변,대 변,잔 액
3,NaN,전기이월,NaN,NaN,899548540,NaN,899548540
4,01-04,ＡＡＢ（주）위너에,98003,기업 185-098540-04-029,180000000,NaN,1079548540
...,...,...,...,...,...,...,...
3029,12-31,화성시주민세,98003,기업 185-098540-04-029,NaN,55000,1327450214
3030,12-31,화성시상수과,98003,기업 185-098540-04-029,NaN,78470,1327371744
3031,12-31,현대캐피탈,98003,기업 185-098540-04-029,NaN,1534610,1325837134
3032,NaN,[ 월 계 ],NaN,NaN,4361292241,4380408091,NaN
3033,NaN,[ 누 계 ],NaN,NaN,54385133407,53059296273,NaN

In [83]:
# 기본설정
월계 = l.iloc[3032,1]
누계 = l.iloc[3033,1]
계정명행 = 1
계정명열 = 6
시작행 = 3

head = l.loc[시작행-1].tolist()

head_replaced = []
for i in head:
    head_replaced.append(i.replace(" ",""))
    
print(head_replaced)
print(월계)
print(누계)

['날짜', '적요란', '코드', '거래처', '차변', '대변', '잔액']
  [ 월         계 ]
  [ 누         계 ]

In [84]:
#리스트 생성
lists = []
lists = [l_2018, l_2019, l_2020, l_2021]
lists

[{'0_보통예금(10300)':         Unnamed: 0                  Unnamed: 1 Unnamed: 2  \
  0              NaN                         NaN        NaN
  1     회사명:(주)위너에코텍                         NaN        NaN
  2               날짜                 적    요    란         코드
  3              NaN                        전기이월        NaN
  4            01-01                        현금입금      98069
  ...            ...                         ...        ...
  4519         12-31                 이자-32-00231      98003
  4520         12-31                      우수사원상금      98003
  4521         12-31  $0.68 * 1,118.10(12/31 환산)      98069
  4522           NaN             [ 월         계 ]        NaN
  4523           NaN             [ 누         계 ]        NaN

              계   정   별   원   장   Unnamed: 4   Unnamed: 5         Unnamed: 6
  0     2018.01.01 ~ 2018.12.31          NaN          NaN                NaN
  1                         NaN          NaN          NaN  계정과목 : [103] 보통예금
  2                         거래처        차   변        대   변              잔   액
  3                         NaN    709984371          NaN          709984371
  4                  신한외화117583        20000          NaN          710004371
  ...                       ...          ...          ...                ...
  4519     기업 185-098540-04-029          NaN        49849          168895548
  4520     기업 185-098540-04-029          NaN       400000          168495548
  4521               신한외화117583          NaN           27          168495521
  4522                      NaN   2707353119   2218661323                NaN
  4523                      NaN  28041547840  27873052319                NaN

  [4524 rows x 7 columns],
  '1_외상매출금(10800)':        Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
  0             NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
  1    회사명:(주)위너에코텍                NaN        NaN                      NaN
  2              날짜        적    요    란         코드                      거래처
  3             NaN               전기이월        NaN                      NaN
  4           01-01                전기분      00175                   하이콘(주)
  ..            ...                ...        ...                      ...
  717         12-31               결산대체      00175                   하이콘(주)
  718         12-31               결산대체      03025       한국남동발전(주) 영동에코발전본부
  719         12-31               결산대체      03109             한국남부발전(주) 본사
  720           NaN    [ 월         계 ]        NaN                      NaN
  721           NaN    [ 누         계 ]        NaN                      NaN

        Unnamed: 4   Unnamed: 5          Unnamed: 6
  0            NaN          NaN                 NaN
  1            NaN          NaN  계정과목 : [108] 외상매출금
  2          차   변        대   변               잔   액
  3     1230514119          NaN          1230514119
  4      100000000          NaN          1330514119
  ..           ...          ...                 ...
  717          NaN    400000000          1760004112
  718          NaN    300000000          1460004112
  719          NaN    100000000          1360004112
  720   1128567210   1534882017                 NaN
  721  14496909109  13136904997                 NaN

  [722 rows x 7 columns],
  '2_단기대여금(11400)':       Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
  0            NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
  1   회사명:(주)위너에코텍                NaN        NaN                      NaN
  2             날짜        적    요    란         코드                      거래처
  3            NaN               전기이월        NaN                      NaN
  4          01-01          가지급금으로 대체      01241                   김대수사장님
  5          01-01          가지급금으로 대체      00358                      한수정
  6          01-01          가지급금으로 대체      01973                      박현정
  7          01-01          가지급금으로 대체      00357                      김인수
  8            NaN    [ 월         계 ]        NaN                      NaN
  9            NaN    [ 누         계 ]        NaN                      NaN
  10         04-18                심우성      03361                      심우성
  11         04-30          （주）에셋매니지먼      02736          （주）에셋매니지먼트그룹홀딩스
  12           NaN    [ 월         계 ]        NaN                      NaN
  13           NaN    [ 누         계 ]        NaN                      NaN
  14         05-30          （주）에셋매니지먼      02736          （주）에셋매니지먼트그룹홀딩스
  15           NaN    [ 월         계 ]        NaN                      NaN
  16           NaN    [ 누         계 ]        NaN                      NaN
  17         06-26                이재원      03216                      이재원
  18           NaN    [ 월         계 ]        NaN                      NaN
  19           NaN    [ 누         계 ]        NaN                      NaN
  20         08-31         (주)에셋매니지먼트      02736          （주）에셋매니지먼트그룹홀딩스
  21           NaN    [ 월         계 ]        NaN                      NaN
  22           NaN    [ 누         계 ]        NaN                      NaN
  23         12-31         단기대여금으로 대체      00358                      한수정
  24         12-31         단기대여금으로 대체      01241                   김대수사장님
  25         12-31         단기대여금으로 대체      01973                      박현정
  26         12-31             급여와 대체      02892                      이상순
  27           NaN    [ 월         계 ]        NaN                      NaN
  28           NaN    [ 누         계 ]        NaN                      NaN

      Unnamed: 4 Unnamed: 5          Unnamed: 6
  0          NaN        NaN                 NaN
  1          NaN        NaN  계정과목 : [114] 단기대여금
  2        차   변      대   변               잔   액
  3   1593269147        NaN          1593269147
  4          NaN  203548478          1389720669
  5          NaN  225559420          1164161249
  6          NaN   40000000          1124161249
  7          NaN  260000000           864161249
  8          NaN  729107898                 NaN
  9   1593269147  729107898                 NaN
  10     1500000        NaN           865661249
  11    54000000        NaN           919661249
  12    55500000        NaN                 NaN
  13  1648769147  729107898                 NaN
  14    26000000        NaN           945661249
  15    26000000        NaN                 NaN
  16  1674769147  729107898                 NaN
  17    20000000        NaN           965661249
  18    20000000        NaN                 NaN
  19  1694769147  729107898                 NaN
  20         NaN   80000000           885661249
  21         NaN   80000000                 NaN
  22  1694769147  809107898                 NaN
  23   207488593        NaN          1093149842
  24    62244221        NaN          1155394063
  25    40000000        NaN          1195394063
  26         NaN   20000000          1175394063
  27   309732814   20000000                 NaN
  28  2004501961  829107898                 NaN  ,
  '3_미수수익(11600)':       Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
  0            NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
  1   회사명:(주)위너에코텍                NaN        NaN                      NaN
  2             날짜        적    요    란         코드                      거래처
  3            NaN               전기이월        NaN                      NaN
  4          12-07          가지급금 인정이자      01973                      박현정
  5          12-31           가지급 인정이자      00357                      김인수
  6          12-31           가지급 인정이자      00358                      한수정
  7          12-31           가지급 인정이자      01973                      박현정
  8          12-31           가지급 인정이자      01241                   김대수사장님
  9          12-31      한수정 가지급금 인정이자      00358                      한수정
  10         12-31     대표이사 가지급금 인정이자      00357                      김인수
  11         12-31     대표이사 가지급금 인정이자      01241                   김대수사장님
  12           NaN    [ 월         계 ]        NaN                      NaN
  13           NaN    [ 누         계 ]        NaN                      NaN

     Unnamed: 4 Unnamed: 5         Unnamed: 6
  0         NaN        NaN                NaN
  1         NaN        NaN  계정과목 : [116] 미수수익
  2       차   변      대   변              잔   액
  3    22446091        NaN           22446091
  4         NaN    1744975           20701116
  5    10106903        NaN           30808019
  6    11314203        NaN           42122222
  7     1559180        NaN           43681402
  8     6159715        NaN           49841117
  9         NaN    7524173           42316944
  10        NaN    9098804           33218140
  11        NaN    4078139           29140001
  12   29140001   22446091                NaN
  13   51586092   22446091                NaN  ,
  '4_미수금(12000)':        Unnamed: 0            Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
  0             NaN                   NaN        NaN  2018.01.01 ~ 2018.12.31
  1    회사명:(주)위너에코텍                   NaN        NaN                      NaN
  2              날짜           적    요    란         코드                      거래처
  3             NaN                  전기이월        NaN                      NaN
  4           01-01              미수금 현금수령      02738                     이에스티
  ..            ...                   ...        ...                      ...
  102         12-31         4/4분기 부가세 환급금      00157                   동안양세무서
  103         12-31  42서4051 그랜저 보험료 미환급액      00365                     삼성화재
  104         12-31                   이현옥      03351                  슈텍E.N.G
  105           NaN       [ 월         계 ]        NaN                      NaN
  106           NaN       [ 누         계 ]        NaN                      NaN

      Unnamed: 4 Unnamed: 5        Unnamed: 6
  0          NaN        NaN               NaN
  1          NaN        NaN  계정과목 : [120] 미수금
  2        차   변      대   변             잔   액
  3       862270        NaN            862270
  4          NaN     271700            590570
  ..         ...        ...               ...
  102   16650319        NaN          22352879
  103      96903        NaN          22449782
  104        NaN     275000          22174782
  105   30014382   14359360               NaN
  106   54828122   32653340               NaN

  [107 rows x 7 columns],
  '5_선급금(13100)':        Unnamed: 0                 Unnamed: 1 Unnamed: 2  \
  0             NaN                        NaN        NaN
  1    회사명:(주)위너에코텍                        NaN        NaN
  2              날짜                적    요    란         코드
  3             NaN                       전기이월        NaN
  4           01-01                         대체      02759
  ..            ...                        ...        ...
  116         12-31                    잡손실로 대체      02725
  117         12-31                    잡손실로 대체      02860
  118         12-31  12/31 $115,200 * 1,118.10      03486
  119           NaN            [ 월         계 ]        NaN
  120           NaN            [ 누         계 ]        NaN

                 계   정   별   원   장  Unnamed: 4  Unnamed: 5        Unnamed: 6
  0        2018.01.01 ~ 2018.12.31         NaN         NaN               NaN
  1                            NaN         NaN         NaN  계정과목 : [131] 선급금
  2                            거래처       차   변       대   변             잔   액
  3                            NaN  1542727154         NaN        1542727154
  4                     주식회사 한솔플러스         NaN      659500        1542067654
  ..                           ...         ...         ...               ...
  116          TECHNIC LIGHTING CO         NaN      933639        1441738187
  117                         땔깜마트         NaN     1000000        1440738187
  118  CLASSICAL NATURAL CTONE(IN)         NaN     1244160        1439494027
  119                          NaN   130049280     3177799               NaN
  120                          NaN  3148176678  1708682651               NaN

  [121 rows x 7 columns],
  '6_선급비용(13300)':      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
  0           NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
  1  회사명:(주)위너에코텍                NaN        NaN                      NaN
  2            날짜        적    요    란         코드                      거래처
  3           NaN               전기이월        NaN                      NaN
  4         01-01         선급비용 재수정분개        NaN                    기간경과분
  5           NaN    [ 월         계 ]        NaN                      NaN
  6           NaN    [ 누         계 ]        NaN                      NaN
  7         12-31        보험료의 선급비용대체        NaN                     미경과분
  8           NaN    [ 월         계 ]        NaN                      NaN
  9           NaN    [ 누         계 ]        NaN                      NaN

    Unnamed: 4 Unnamed: 5         Unnamed: 6
  0        NaN        NaN                NaN
  1        NaN        NaN  계정과목 : [133] 선급비용
  2      차   변      대   변              잔   액
  3    6808199        NaN            6808199
  4        NaN    6808199                NaN
  5        NaN    6808199                NaN
  6    6808199    6808199                NaN
  7    5833840        NaN            5833840
  8    5833840        NaN                NaN
  9   12642039    6808199                NaN  ,
  '7_가지급금(13400)':       Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
  0            NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
  1   회사명:(주)위너에코텍                NaN        NaN                      NaN
  2             날짜        적    요    란         코드                      거래처
  3          01-01         단기대여금에서 대체      01241                   김대수사장님
  4          01-01         단기대여금에서 대체      00358                      한수정
  ..           ...                ...        ...                      ...
  56         12-31          가지급금에서 대체      00358                      한수정
  57         12-31          가지급금에서 대체      01241                   김대수사장님
  58         12-31          가지급금에서 대체      01973                      박현정
  59           NaN    [ 월         계 ]        NaN                      NaN
  60           NaN    [ 누         계 ]        NaN                      NaN

     Unnamed: 4 Unnamed: 5         Unnamed: 6
  0         NaN        NaN                NaN
  1         NaN        NaN  계정과목 : [134] 가지급금
  2       차   변      대   변              잔   액
  3   203548478        NaN          203548478
  4   225559420        NaN          429107898
  ..        ...        ...                ...
  56        NaN  207488593          102244221
  57        NaN   62244221           40000000
  58        NaN   40000000                NaN
  59    4000000  798506698                NaN
  60  882572598  882572598                NaN

  [61 rows x 7 columns],
  '8_부가세대급금(13500)':         Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
  0              NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
  1     회사명:(주)위너에코텍                NaN        NaN                      NaN
  2               날짜        적    요    란         코드                      거래처
  3            01-01       월정료 (201802)      02616           (주)에이디티캡스 화성지사
  4            01-01       월정료 (201801)      01989           (주)에이디티캡스 용인지사
  ...            ...                ...        ...                      ...
  1991         12-31              코아가공대      00535                 웅진정밀/이의청
  1992         12-31               조립대금      03432                     일승전자
  1993         12-31         부가세예수금과 상계        NaN                      NaN
  1994           NaN    [ 월         계 ]        NaN                      NaN
  1995           NaN    [ 누         계 ]        NaN                      NaN

       Unnamed: 4 Unnamed: 5           Unnamed: 6
  0           NaN        NaN                  NaN
  1           NaN        NaN  계정과목 : [135] 부가세대급금
  2         차   변      대   변                잔   액
  3          5150        NaN                 5150
  4          9500        NaN                14650
  ...         ...        ...                  ...
  1991    1851000        NaN            249484039
  1992      94149        NaN            249578188
  1993        NaN  249578188                  NaN
  1994  111874615  249578188                  NaN
  1995  866867191  866867191                  NaN

  [1996 rows x 7 columns],
  '9_선납세금(13600)':       Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
  0            NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
  1   회사명:(주)위너에코텍                NaN        NaN                      NaN
  2             날짜        적    요    란         코드                      거래처
  3            NaN               전기이월        NaN                      NaN
  4          01-22        이자소득 원천징수세액      00157                   동안양세무서
  5          01-22        이자소득 원천징수세액      03217                     동안구청
  6            NaN    [ 월         계 ]        NaN                      NaN
  7            NaN    [ 누         계 ]        NaN                      NaN
  8          03-25        이자소득 원천징수세액      00157                   동안양세무서
  9          03-25        이자소득 원천징수세액      03217                     동안구청
  10         03-30        이자소득 원천징수세액      00157                   동안양세무서
  11         03-30        이자소득 원천징수세액      03217                     동안구청
  12           NaN    [ 월         계 ]        NaN                      NaN
  13           NaN    [ 누         계 ]        NaN                      NaN
  14         04-19             동안양세무서      00157                   동안양세무서
  15         04-30        이자소득 원천징수세액      00157                   동안양세무서
  16         04-30        이자소득 원천징수세액      03217                     동안구청
  17           NaN    [ 월         계 ]        NaN                      NaN
  18           NaN    [ 누         계 ]        NaN                      NaN
  19         05-29             동안세무환급      03217                     동안구청
  20           NaN    [ 월         계 ]        NaN                      NaN
  21           NaN    [ 누         계 ]        NaN                      NaN
  22         06-24        이자소득 원천징수세액      00157                   동안양세무서
  23         06-24        이자소득 원천징수세액      03217                     동안구청
  24           NaN    [ 월         계 ]        NaN                      NaN
  25           NaN    [ 누         계 ]        NaN                      NaN
  26         07-12        이자소득 원천징수세액      00157                   동안양세무서
  27         07-12        이자소득 원천징수세액      03217                     동안구청
  28           NaN    [ 월         계 ]        NaN                      NaN
  29           NaN    [ 누         계 ]        NaN                      NaN
  30         08-08        이자소득 원천징수세액      00157                   동안양세무서
  31         08-08        이자소득 원천징수세액      03217                     동안구청
  32           NaN    [ 월         계 ]        NaN                      NaN
  33           NaN    [ 누         계 ]        NaN                      NaN
  34         09-23        이자소득 원천징수세액      00157                   동안양세무서
  35         09-23        이자소득 원천징수세액      03217                     동안구청
  36           NaN    [ 월         계 ]        NaN                      NaN
  37           NaN    [ 누         계 ]        NaN                      NaN
  38         12-18        이자소득 원천징수세액      00157                   동안양세무서
  39         12-18        이자소득 원천징수세액      03217                     동안구청
  40         12-23        이자소득 원천징수세액      00157                   동안양세무서
  41         12-23        이자소득 원천징수세액      03217                     동안구청
  42           NaN    [ 월         계 ]        NaN                      NaN
  43           NaN    [ 누         계 ]        NaN                      NaN

     Unnamed: 4 Unnamed: 5         Unnamed: 6
  0         NaN        NaN                NaN
  1         NaN        NaN  계정과목 : [136] 선납세금
  2       차   변      대   변              잔   액
  3      426620        NaN             426620
  4       12700        NaN             439320

In [5]:
#데이터프레임생성
df = pd.DataFrame(columns = head_replaced)
df['년'] = ""
df['계정명'] = ""

In [85]:
#데이터프레임생성_v2
df2 = pd.DataFrame(columns = head_replaced)
df2['년'] = ""
df2['계정명'] = ""

In [22]:
#변수 자동 설정 >>> 이거 쓸 수 있음!!
for i in range(1,3):
    globals()['Var_{}'.format(i)] = i
    
print(Var_1)

1

In [88]:
#파일반복 > i
for i in range(len(lists)):
    
    #리스트 이름에서 년도 추출
    vnames = [name for name in globals() if globals()[name] is lists[i]]
    year = str(vnames)[-6:-2]
    
    sheets = list(lists[i].keys())
    
    #파일 내 시트반복 > j
    for j in range(len(sheets)):
        sheet = lists[i][sheets[j]]
        
        계정명 = sheet.iloc[계정명행,계정명열]
        계정명 = 계정명.replace("계정과목","")
        계정명 = 계정명.replace(":","")
        계정명 = 계정명.replace(" ","")
        
        #시트 내 데이터프레임 추가

        Unnamed: 0                  Unnamed: 1 Unnamed: 2  \
0              NaN                         NaN        NaN
1     회사명:(주)위너에코텍                         NaN        NaN
2               날짜                 적    요    란         코드
3              NaN                        전기이월        NaN
4            01-01                        현금입금      98069
...            ...                         ...        ...
4519         12-31                 이자-32-00231      98003
4520         12-31                      우수사원상금      98003
4521         12-31  $0.68 * 1,118.10(12/31 환산)      98069
4522           NaN             [ 월         계 ]        NaN
4523           NaN             [ 누         계 ]        NaN

            계   정   별   원   장   Unnamed: 4   Unnamed: 5         Unnamed: 6
0     2018.01.01 ~ 2018.12.31          NaN          NaN                NaN
1                         NaN          NaN          NaN  계정과목 : [103] 보통예금
2                         거래처        차   변        대   변              잔   액
3                         NaN    709984371          NaN          709984371
4                  신한외화117583        20000          NaN          710004371
...                       ...          ...          ...                ...
4519     기업 185-098540-04-029          NaN        49849          168895548
4520     기업 185-098540-04-029          NaN       400000          168495548
4521               신한외화117583          NaN           27          168495521
4522                      NaN   2707353119   2218661323                NaN
4523                      NaN  28041547840  27873052319                NaN

[4524 rows x 7 columns]
       Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0             NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
1    회사명:(주)위너에코텍                NaN        NaN                      NaN
2              날짜        적    요    란         코드                      거래처
3             NaN               전기이월        NaN                      NaN
4           01-01                전기분      00175                   하이콘(주)
..            ...                ...        ...                      ...
717         12-31               결산대체      00175                   하이콘(주)
718         12-31               결산대체      03025       한국남동발전(주) 영동에코발전본부
719         12-31               결산대체      03109             한국남부발전(주) 본사
720           NaN    [ 월         계 ]        NaN                      NaN
721           NaN    [ 누         계 ]        NaN                      NaN

      Unnamed: 4   Unnamed: 5          Unnamed: 6
0            NaN          NaN                 NaN
1            NaN          NaN  계정과목 : [108] 외상매출금
2          차   변        대   변               잔   액
3     1230514119          NaN          1230514119
4      100000000          NaN          1330514119
..           ...          ...                 ...
717          NaN    400000000          1760004112
718          NaN    300000000          1460004112
719          NaN    100000000          1360004112
720   1128567210   1534882017                 NaN
721  14496909109  13136904997                 NaN

[722 rows x 7 columns]
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3            NaN               전기이월        NaN                      NaN
4          01-01          가지급금으로 대체      01241                   김대수사장님
5          01-01          가지급금으로 대체      00358                      한수정
6          01-01          가지급금으로 대체      01973                      박현정
7          01-01          가지급금으로 대체      00357                      김인수
8            NaN    [ 월         계 ]        NaN                      NaN
9            NaN    [ 누         계 ]        NaN                      NaN
10         04-18                심우성      03361                      심우성
11         04-30          （주）에셋매니지먼      02736          （주）에셋매니지먼트그룹홀딩스
12           NaN    [ 월         계 ]        NaN                      NaN
13           NaN    [ 누         계 ]        NaN                      NaN
14         05-30          （주）에셋매니지먼      02736          （주）에셋매니지먼트그룹홀딩스
15           NaN    [ 월         계 ]        NaN                      NaN
16           NaN    [ 누         계 ]        NaN                      NaN
17         06-26                이재원      03216                      이재원
18           NaN    [ 월         계 ]        NaN                      NaN
19           NaN    [ 누         계 ]        NaN                      NaN
20         08-31         (주)에셋매니지먼트      02736          （주）에셋매니지먼트그룹홀딩스
21           NaN    [ 월         계 ]        NaN                      NaN
22           NaN    [ 누         계 ]        NaN                      NaN
23         12-31         단기대여금으로 대체      00358                      한수정
24         12-31         단기대여금으로 대체      01241                   김대수사장님
25         12-31         단기대여금으로 대체      01973                      박현정
26         12-31             급여와 대체      02892                      이상순
27           NaN    [ 월         계 ]        NaN                      NaN
28           NaN    [ 누         계 ]        NaN                      NaN

    Unnamed: 4 Unnamed: 5          Unnamed: 6
0          NaN        NaN                 NaN
1          NaN        NaN  계정과목 : [114] 단기대여금
2        차   변      대   변               잔   액
3   1593269147        NaN          1593269147
4          NaN  203548478          1389720669
5          NaN  225559420          1164161249
6          NaN   40000000          1124161249
7          NaN  260000000           864161249
8          NaN  729107898                 NaN
9   1593269147  729107898                 NaN
10     1500000        NaN           865661249
11    54000000        NaN           919661249
12    55500000        NaN                 NaN
13  1648769147  729107898                 NaN
14    26000000        NaN           945661249
15    26000000        NaN                 NaN
16  1674769147  729107898                 NaN
17    20000000        NaN           965661249
18    20000000        NaN                 NaN
19  1694769147  729107898                 NaN
20         NaN   80000000           885661249
21         NaN   80000000                 NaN
22  1694769147  809107898                 NaN
23   207488593        NaN          1093149842
24    62244221        NaN          1155394063
25    40000000        NaN          1195394063
26         NaN   20000000          1175394063
27   309732814   20000000                 NaN
28  2004501961  829107898                 NaN
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3            NaN               전기이월        NaN                      NaN
4          12-07          가지급금 인정이자      01973                      박현정
5          12-31           가지급 인정이자      00357                      김인수
6          12-31           가지급 인정이자      00358                      한수정
7          12-31           가지급 인정이자      01973                      박현정
8          12-31           가지급 인정이자      01241                   김대수사장님
9          12-31      한수정 가지급금 인정이자      00358                      한수정
10         12-31     대표이사 가지급금 인정이자      00357                      김인수
11         12-31     대표이사 가지급금 인정이자      01241                   김대수사장님
12           NaN    [ 월         계 ]        NaN                      NaN
13           NaN    [ 누         계 ]        NaN                      NaN

   Unnamed: 4 Unnamed: 5         Unnamed: 6
0         NaN        NaN                NaN
1         NaN        NaN  계정과목 : [116] 미수수익
2       차   변      대   변              잔   액
3    22446091        NaN           22446091
4         NaN    1744975           20701116
5    10106903        NaN           30808019
6    11314203        NaN           42122222
7     1559180        NaN           43681402
8     6159715        NaN           49841117
9         NaN    7524173           42316944
10        NaN    9098804           33218140
11        NaN    4078139           29140001
12   29140001   22446091                NaN
13   51586092   22446091                NaN
       Unnamed: 0            Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0             NaN                   NaN        NaN  2018.01.01 ~ 2018.12.31
1    회사명:(주)위너에코텍                   NaN        NaN                      NaN
2              날짜           적    요    란         코드                      거래처
3             NaN                  전기이월        NaN                      NaN
4           01-01              미수금 현금수령      02738                     이에스티
..            ...                   ...        ...                      ...
102         12-31         4/4분기 부가세 환급금      00157                   동안양세무서
103         12-31  42서4051 그랜저 보험료 미환급액      00365                     삼성화재
104         12-31                   이현옥      03351                  슈텍E.N.G
105           NaN       [ 월         계 ]        NaN                      NaN
106           NaN       [ 누         계 ]        NaN                      NaN

    Unnamed: 4 Unnamed: 5        Unnamed: 6
0          NaN        NaN               NaN
1          NaN        NaN  계정과목 : [120] 미수금
2        차   변      대   변             잔   액
3       862270        NaN            862270
4          NaN     271700            590570
..         ...        ...               ...
102   16650319        NaN          22352879
103      96903        NaN          22449782
104        NaN     275000          22174782
105   30014382   14359360               NaN
106   54828122   32653340               NaN

[107 rows x 7 columns]
       Unnamed: 0                 Unnamed: 1 Unnamed: 2  \
0             NaN                        NaN        NaN
1    회사명:(주)위너에코텍                        NaN        NaN
2              날짜                적    요    란         코드
3             NaN                       전기이월        NaN
4           01-01                         대체      02759
..            ...                        ...        ...
116         12-31                    잡손실로 대체      02725
117         12-31                    잡손실로 대체      02860
118         12-31  12/31 $115,200 * 1,118.10      03486
119           NaN            [ 월         계 ]        NaN
120           NaN            [ 누         계 ]        NaN

               계   정   별   원   장  Unnamed: 4  Unnamed: 5        Unnamed: 6
0        2018.01.01 ~ 2018.12.31         NaN         NaN               NaN
1                            NaN         NaN         NaN  계정과목 : [131] 선급금
2                            거래처       차   변       대   변             잔   액
3                            NaN  1542727154         NaN        1542727154
4                     주식회사 한솔플러스         NaN      659500        1542067654
..                           ...         ...         ...               ...
116          TECHNIC LIGHTING CO         NaN      933639        1441738187
117                         땔깜마트         NaN     1000000        1440738187
118  CLASSICAL NATURAL CTONE(IN)         NaN     1244160        1439494027
119                          NaN   130049280     3177799               NaN
120                          NaN  3148176678  1708682651               NaN

[121 rows x 7 columns]
     Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0           NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
1  회사명:(주)위너에코텍                NaN        NaN                      NaN
2            날짜        적    요    란         코드                      거래처
3           NaN               전기이월        NaN                      NaN
4         01-01         선급비용 재수정분개        NaN                    기간경과분
5           NaN    [ 월         계 ]        NaN                      NaN
6           NaN    [ 누         계 ]        NaN                      NaN
7         12-31        보험료의 선급비용대체        NaN                     미경과분
8           NaN    [ 월         계 ]        NaN                      NaN
9           NaN    [ 누         계 ]        NaN                      NaN

  Unnamed: 4 Unnamed: 5         Unnamed: 6
0        NaN        NaN                NaN
1        NaN        NaN  계정과목 : [133] 선급비용
2      차   변      대   변              잔   액
3    6808199        NaN            6808199
4        NaN    6808199                NaN
5        NaN    6808199                NaN
6    6808199    6808199                NaN
7    5833840        NaN            5833840
8    5833840        NaN                NaN
9   12642039    6808199                NaN
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3          01-01         단기대여금에서 대체      01241                   김대수사장님
4          01-01         단기대여금에서 대체      00358                      한수정
..           ...                ...        ...                      ...
56         12-31          가지급금에서 대체      00358                      한수정
57         12-31          가지급금에서 대체      01241                   김대수사장님
58         12-31          가지급금에서 대체      01973                      박현정
59           NaN    [ 월         계 ]        NaN                      NaN
60           NaN    [ 누         계 ]        NaN                      NaN

   Unnamed: 4 Unnamed: 5         Unnamed: 6
0         NaN        NaN                NaN
1         NaN        NaN  계정과목 : [134] 가지급금
2       차   변      대   변              잔   액
3   203548478        NaN          203548478
4   225559420        NaN          429107898
..        ...        ...                ...
56        NaN  207488593          102244221
57        NaN   62244221           40000000
58        NaN   40000000                NaN
59    4000000  798506698                NaN
60  882572598  882572598                NaN

[61 rows x 7 columns]
        Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0              NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
1     회사명:(주)위너에코텍                NaN        NaN                      NaN
2               날짜        적    요    란         코드                      거래처
3            01-01       월정료 (201802)      02616           (주)에이디티캡스 화성지사
4            01-01       월정료 (201801)      01989           (주)에이디티캡스 용인지사
...            ...                ...        ...                      ...
1991         12-31              코아가공대      00535                 웅진정밀/이의청
1992         12-31               조립대금      03432                     일승전자
1993         12-31         부가세예수금과 상계        NaN                      NaN
1994           NaN    [ 월         계 ]        NaN                      NaN
1995           NaN    [ 누         계 ]        NaN                      NaN

     Unnamed: 4 Unnamed: 5           Unnamed: 6
0           NaN        NaN                  NaN
1           NaN        NaN  계정과목 : [135] 부가세대급금
2         차   변      대   변                잔   액
3          5150        NaN                 5150
4          9500        NaN                14650
...         ...        ...                  ...
1991    1851000        NaN            249484039
1992      94149        NaN            249578188
1993        NaN  249578188                  NaN
1994  111874615  249578188                  NaN
1995  866867191  866867191                  NaN

[1996 rows x 7 columns]
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3            NaN               전기이월        NaN                      NaN
4          01-22        이자소득 원천징수세액      00157                   동안양세무서
5          01-22        이자소득 원천징수세액      03217                     동안구청
6            NaN    [ 월         계 ]        NaN                      NaN
7            NaN    [ 누         계 ]        NaN                      NaN
8          03-25        이자소득 원천징수세액      00157                   동안양세무서
9          03-25        이자소득 원천징수세액      03217                     동안구청
10         03-30        이자소득 원천징수세액      00157                   동안양세무서
11         03-30        이자소득 원천징수세액      03217                     동안구청
12           NaN    [ 월         계 ]        NaN                      NaN
13           NaN    [ 누         계 ]        NaN                      NaN
14         04-19             동안양세무서      00157                   동안양세무서
15         04-30        이자소득 원천징수세액      00157                   동안양세무서
16         04-30        이자소득 원천징수세액      03217                     동안구청
17           NaN    [ 월         계 ]        NaN                      NaN
18           NaN    [ 누         계 ]        NaN                      NaN
19         05-29             동안세무환급      03217                     동안구청
20           NaN    [ 월         계 ]        NaN                      NaN
21           NaN    [ 누         계 ]        NaN                      NaN
22         06-24        이자소득 원천징수세액      00157                   동안양세무서
23         06-24        이자소득 원천징수세액      03217                     동안구청
24           NaN    [ 월         계 ]        NaN                      NaN
25           NaN    [ 누         계 ]        NaN                      NaN
26         07-12        이자소득 원천징수세액      00157                   동안양세무서
27         07-12        이자소득 원천징수세액      03217                     동안구청
28           NaN    [ 월         계 ]        NaN                      NaN
29           NaN    [ 누         계 ]        NaN                      NaN
30         08-08        이자소득 원천징수세액      00157                   동안양세무서
31         08-08        이자소득 원천징수세액      03217                     동안구청
32           NaN    [ 월         계 ]        NaN                      NaN
33           NaN    [ 누         계 ]        NaN                      NaN
34         09-23        이자소득 원천징수세액      00157                   동안양세무서
35         09-23        이자소득 원천징수세액      03217                     동안구청
36           NaN    [ 월         계 ]        NaN                      NaN
37           NaN    [ 누         계 ]        NaN                      NaN
38         12-18        이자소득 원천징수세액      00157                   동안양세무서
39         12-18        이자소득 원천징수세액      03217                     동안구청
40         12-23        이자소득 원천징수세액      00157                   동안양세무서
41         12-23        이자소득 원천징수세액      03217                     동안구청
42           NaN    [ 월         계 ]        NaN                      NaN
43           NaN    [ 누         계 ]        NaN                      NaN

   Unnamed: 4 Unnamed: 5         Unnamed: 6
0         NaN        NaN                NaN
1         NaN        NaN  계정과목 : [136] 선납세금
2       차   변      대   변              잔   액
3      426620        NaN             426620
4       12700        NaN             439320
5        1270        NaN             440590
6       13970        NaN                NaN
7      440590        NaN                NaN
8        8550        NaN             449140
9         850        NaN             449990
10     126110        NaN             576100
11      12610        NaN             588710
12     148120        NaN                NaN
13     588710        NaN                NaN
14        NaN     387920             200790
15      71880        NaN             272670
16       7180        NaN             279850
17      79060     387920                NaN
18     667770     387920                NaN
19        NaN      38700             241150
20        NaN      38700                NaN
21     667770     426620                NaN
22       2600        NaN             243750
23        260        NaN             244010

6        NaN    3724775                 NaN
     Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0           NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
1  회사명:(주)위너에코텍                NaN        NaN                      NaN
2            날짜        적    요    란         코드                      거래처
3         08-16          상환주식 매각처분        NaN                      NaN
4           NaN    [ 월         계 ]        NaN                      NaN
5           NaN    [ 누         계 ]        NaN                      NaN
6         12-31      미처분 이익잉여금에 대체        NaN                      NaN
7           NaN    [ 월         계 ]        NaN                      NaN
8           NaN    [ 누         계 ]        NaN                      NaN

   Unnamed: 4  Unnamed: 5             Unnamed: 6
0         NaN         NaN                    NaN
1         NaN         NaN  계정과목 : [361] 상환주식의상환액
2       차   변       대   변                  잔   액
3  1186258502         NaN            -1186258502
4  1186258502         NaN                    NaN
5  1186258502         NaN                    NaN
6         NaN  1186258502                    NaN
7         NaN  1186258502                    NaN
8  1186258502  1186258502                    NaN
     Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0           NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
1  회사명:(주)위너에코텍                NaN        NaN                      NaN
2            날짜        적    요    란         코드                      거래처
3         01-01  전기오류(17.03.20 매각)      98101                 트러스톤칭키스칸
4           NaN    [ 월         계 ]        NaN                      NaN
5           NaN    [ 누         계 ]        NaN                      NaN
6         12-31      미처분 이익잉여금에 대체        NaN                      NaN
7           NaN    [ 월         계 ]        NaN                      NaN
8           NaN    [ 누         계 ]        NaN                      NaN

  Unnamed: 4 Unnamed: 5             Unnamed: 6
0        NaN        NaN                    NaN
1        NaN        NaN  계정과목 : [370] 전기오류수정이익
2      차   변      대   변                  잔   액
3        NaN      79634                  79634
4        NaN      79634                    NaN
5        NaN      79634                    NaN
6      79634        NaN                    NaN
7      79634        NaN                    NaN
8      79634      79634                    NaN
     Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0           NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
1  회사명:(주)위너에코텍                NaN        NaN                      NaN
2            날짜        적    요    란         코드                      거래처
3         01-01              전기오류분      02238          STJ BATTERY INC
4           NaN    [ 월         계 ]        NaN                      NaN
5           NaN    [ 누         계 ]        NaN                      NaN
6         12-31      미처분 이익잉여금에 대체        NaN                      NaN
7           NaN    [ 월         계 ]        NaN                      NaN
8           NaN    [ 누         계 ]        NaN                      NaN

  Unnamed: 4 Unnamed: 5             Unnamed: 6
0        NaN        NaN                    NaN
1        NaN        NaN  계정과목 : [371] 전기오류수정손실
2      차   변      대   변                  잔   액
3  136311376        NaN              136311376
4  136311376        NaN                    NaN
5  136311376        NaN                    NaN
6        NaN  136311376                    NaN
7        NaN  136311376                    NaN
8  136311376  136311376                    NaN
      Unnamed: 0             Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                    NaN        NaN  2018.01.01 ~ 2018.12.31
1   회사명:(주)위너에코텍                    NaN        NaN                      NaN
2             날짜            적    요    란         코드                      거래처
3          04-30  기보 우선주 999주 매입대금 중 일부      00180                 (주)위너에코텍
4            NaN        [ 월         계 ]        NaN                      NaN
5            NaN        [ 누         계 ]        NaN                      NaN
6          05-31  기보 우선주 999주 매입대금 중 잔액      00180                 (주)위너에코텍
7            NaN        [ 월         계 ]        NaN                      NaN
8            NaN        [ 누         계 ]        NaN                      NaN
9          08-16              상환주식 매각처분        NaN                      NaN
10           NaN        [ 월         계 ]        NaN                      NaN
11           NaN        [ 누         계 ]        NaN                      NaN

    Unnamed: 4  Unnamed: 5         Unnamed: 6
0          NaN         NaN                NaN
1          NaN         NaN  계정과목 : [373] 자기주식
2        차   변       대   변              잔   액
3    500000000         NaN         -500000000
4    500000000         NaN                NaN
5    500000000         NaN                NaN
6    686258502         NaN        -1186258502
7    686258502         NaN                NaN
8   1186258502         NaN                NaN
9          NaN  1186258502                NaN
10         NaN  1186258502                NaN
11  1186258502  1186258502                NaN
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3            NaN               전기이월        NaN                      NaN
4          03-31        이익잉여금 배당처분액        NaN                      NaN
5            NaN    [ 월         계 ]        NaN                      NaN
6            NaN    [ 누         계 ]        NaN                      NaN
7          12-31          차기이월이익잉여금        NaN                      NaN
8          12-31     미처분 이익잉여금에서 대체        NaN                      NaN
9            NaN    [ 월         계 ]        NaN                      NaN
10           NaN    [ 누         계 ]        NaN                      NaN

    Unnamed: 4  Unnamed: 5            Unnamed: 6
0          NaN         NaN                   NaN
1          NaN         NaN  계정과목 : [375] 이월이익잉여금
2        차   변       대   변                 잔   액
3          NaN  3133193955            3133193955
4        54945         NaN            3133139010
5        54945         NaN                   NaN
6        54945  3133193955                   NaN
7          NaN  2183110075            5316249085
8   3133139010         NaN            2183110075
9   3133139010  2183110075                   NaN
10  3133193955  5316304030                   NaN
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3          12-31      전기오류수정이익에서 대체        NaN                      NaN
4          12-31           당기순손익 대체        NaN                      NaN
5          12-31        이월이익잉여금에 대체        NaN                      NaN
6          12-31      전기오류수정손실에서 대체        NaN                      NaN
7          12-31      상환주식의상환액에서 대체        NaN                      NaN
8          12-31       이월이익잉여금에서 대체        NaN                      NaN
9            NaN    [ 월         계 ]        NaN                      NaN
10           NaN    [ 누         계 ]        NaN                      NaN

    Unnamed: 4  Unnamed: 5             Unnamed: 6
0          NaN         NaN                    NaN
1          NaN         NaN  계정과목 : [377] 미처분이익잉여금
2        차   변       대   변                  잔   액
3          NaN       79634                  79634
4          NaN   372461309              372540943
5          NaN  3133139010             3505679953
6    136311376         NaN             3369368577
7   1186258502         NaN             2183110075
8   2183110075         NaN                    NaN
9   3505679953  3505679953                    NaN
10  3505679953  3505679953                    NaN
     Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0           NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
1  회사명:(주)위너에코텍                NaN        NaN                      NaN
2            날짜        적    요    란         코드                      거래처
3         12-31            수익에서 대체        NaN                      NaN
4         12-31            비용에서 대체        NaN                      NaN
5         12-31      당기순손익 잉여금에 대체        NaN                      NaN
6           NaN    [ 월         계 ]        NaN                      NaN
7           NaN    [ 누         계 ]        NaN                      NaN

    Unnamed: 4   Unnamed: 5       Unnamed: 6
0          NaN          NaN              NaN
1          NaN          NaN  계정과목 : [400] 손익
2        차   변        대   변            잔   액
3          NaN  12087747186      12087747186
4  11715285877          NaN        372461309
5    372461309          NaN              NaN
6  12087747186  12087747186              NaN
7  12087747186  12087747186              NaN
      Unnamed: 0                          Unnamed: 1 Unnamed: 2  \
0            NaN                                 NaN        NaN
1   회사명:(주)위너에코텍                                 NaN        NaN
2             날짜                         적    요    란         코드
3          01-31  $312,679.58 * 1,071.50 WOOD PELLET      03109
4            NaN                     [ 월         계 ]        NaN
5            NaN                     [ 누         계 ]        NaN
6          02-19                         WOOD PELLET      03025
7          02-19                         WOOD PELLET      03025
8          02-19   $917,620.62 *1,079.90 WOOD PELLET      03025
9            NaN                     [ 월         계 ]        NaN
10           NaN                     [ 누         계 ]        NaN
11         03-30  $290,352.48 * 1,066.50 WOOD PELLET      03109
12         03-30  $101,693.78 * 1,066.50 WOOD PELLET      03025
13           NaN                     [ 월         계 ]        NaN
14           NaN                     [ 누         계 ]        NaN
15         04-25                         WOOD PELLET      03025
16         04-25                         WOOD PELLET      03025
17         04-27  $173,229.01 * 1,079.70 WOOD PELLET      03025
18           NaN                     [ 월         계 ]        NaN
19           NaN                     [ 누         계 ]        NaN
20         05-17                         WOOD PELLET      03025
21         05-17                         WOOD PELLET      03025
22         05-23                         WOOD PELLET      03025
23         05-23                         WOOD PELLET      03025
24         05-23  $852,940.04 * 1,083.80 WOOD PELLET      03025
25         05-23                         WOOD PELLET      03025
26         05-29                         WOOD PELLET      03025
27         05-31             우드펠릿 1,656.58 X 178,500      03288
28           NaN                     [ 월         계 ]        NaN
29           NaN                     [ 누         계 ]        NaN
30         06-14   $90,309.12 * 1,075.10 WOOD PELLET      03025
31           NaN                     [ 월         계 ]        NaN
32           NaN                     [ 누         계 ]        NaN
33         08-21      WOOD PELLET 424.92 X 169,376.7      03343
34         08-24      WOOD PELLET 496.69 X 169,240.8      03343
35           NaN                     [ 월         계 ]        NaN
36           NaN                     [ 누         계 ]        NaN
37         09-06      WOOD PELLET 499.55 X 168,757.6      03343
38         09-07                  우드펠릿 929 X 155,000      03288
39         09-07               우드펠릿 -836.1 X 155,000      03288
40         09-07                우드펠릿 836.1 X 155,000      03288
41         09-13               우드펠릿 -84.72 X 155,000      03288
42         09-13                                우드펠릿      03288
43         09-13                우드펠릿 84.72 X 155,000      03288
44         09-17      WOOD PELLET 670.24 X 168,999.2      03343
45         09-17                우드펠릿 84.72 X 155,000      03288
46         09-17               우드펠릿 -84.72 X 155,000      03288
47           NaN                     [ 월         계 ]        NaN
48           NaN                     [ 누         계 ]        NaN
49         10-15                         WOOD PELLET      03415
50           NaN                     [ 월         계 ]        NaN
51           NaN                     [ 누         계 ]        NaN
52         12-31         WOOD PELLET 24.05 X 190,000      03429
53         12-31        WOOD PELLET 478.59 X 157,000      03430
54         12-31        WOOD PELLET 479.16 X 157,000      03430
55         12-31        WOOD PELLET 479.16 X 157,000      03430
56         12-31                            손익계정에 대체        NaN
57           NaN                     [ 월         계 ]        NaN
58           NaN                     [ 누         계 ]        NaN

          계   정   별   원   장  Unnamed: 4  Unnamed: 5         Unnamed: 6
0   2018.01.01 ~ 2018.12.31         NaN         NaN                NaN
1                       NaN         NaN         NaN  계정과목 : [401] 상품매출
2                       거래처       차   변       대   변              잔   액
3              한국남부발전(주) 본사         NaN   301678940          301678940
4                       NaN         NaN   301678940                NaN
5                       NaN         NaN   301678940                NaN
6        한국남동발전(주) 영동에코발전본부         NaN   900853185         1202532125
7        한국남동발전(주) 영동에코발전본부         NaN  -900853184          301678941
8        한국남동발전(주) 영동에코발전본부         NaN   900853184         1202532125
9                       NaN         NaN   900853185                NaN
10                      NaN         NaN  1202532125                NaN
11             한국남부발전(주) 본사         NaN   281509927         1484042052
12       한국남동발전(주) 영동에코발전본부         NaN    98596741         1582638793
13                      NaN         NaN   380106668                NaN
14                      NaN         NaN  1582638793                NaN
15       한국남동발전(주) 영동에코발전본부         NaN  -169591289         1413047504
16       한국남동발전(주) 영동에코발전본부         NaN   169591289         1582638793
17       한국남동발전(주) 영동에코발전본부         NaN   170032236         1752671029
18                      NaN         NaN   170032236                NaN
19                      NaN         NaN  1752671029                NaN
20       한국남동발전(주) 영동에코발전본부         NaN  -836424023          916247006
21       한국남동발전(주) 영동에코발전본부         NaN   836424023         1752671029
22       한국남동발전(주) 영동에코발전본부         NaN   836424023         2589095052
23       한국남동발전(주) 영동에코발전본부         NaN   840378563         3429473615
24       한국남동발전(주) 영동에코발전본부         NaN   840378563         4269852178
25       한국남동발전(주) 영동에코발전본부         NaN  -836424023         3433428155
26       한국남동발전(주) 영동에코발전본부         NaN  -840378563         2593049592
27               (주)대림코퍼레이션         NaN   295699530         2888749122
28                      NaN         NaN  1136078093                NaN
29                      NaN         NaN  2888749122                NaN
30       한국남동발전(주) 영동에코발전본부         NaN    88264850         2977013972
31                      NaN         NaN    88264850                NaN
32                      NaN         NaN  2977013972                NaN
33                주식회사 파이니어         NaN    71971547         3048985519
34                주식회사 파이니어         NaN    84060213         3133045732
35                      NaN         NaN   156031760                NaN
36                      NaN         NaN  3133045732                NaN
37                주식회사 파이니어         NaN    84302859         3217348591
38               (주)대림코퍼레이션         NaN   143995000         3361343591
39               (주)대림코퍼레이션         NaN  -129595500         3231748091
40               (주)대림코퍼레이션         NaN   129595500         3361343591
41               (주)대림코퍼레이션         NaN   -13131600         3348211991
42               (주)대림코퍼레이션         NaN    -1267900         3346944091
43               (주)대림코퍼레이션         NaN    13131600         3360075691
44                주식회사 파이니어         NaN   113270024         3473345715
45               (주)대림코퍼레이션         NaN    13131600         3486477315
46               (주)대림코퍼레이션         NaN   -13131600         3473345715
47                      NaN         NaN   340299983                NaN
48                      NaN         NaN  3473345715                NaN
49                 (주)현대리바트         NaN   203596227         3676941942
50                      NaN         NaN   203596227                NaN
51                      NaN         NaN  3676941942                NaN
52              유한회사 진승로지스틱         NaN     3956225         3680898167
53               주식회사 이엔피에스         NaN    75138630         3756036797
54               주식회사 이엔피에스         NaN   -75228120         3680808677
55               주식회사 이엔피에스         NaN    75228120         3756036797
56                      NaN  3756036797         NaN                NaN
57                      NaN  3756036797    79094855                NaN
58                      NaN  3756036797  3756036797                NaN
       Unnamed: 0                  Unnamed: 1 Unnamed: 2  \
0             NaN                         NaN        NaN
1    회사명:(주)위너에코텍                         NaN        NaN
2              날짜                 적    요    란         코드
3           01-15  IR FRONT ASSY 300 X 19,700      00124
4           01-18        MALE 30P 1,000 X 810      02609
..            ...                         ...        ...
377         12-31                        물품대금      00851
378         12-31                        금형대금      00178
379         12-31                    손익계정에 대체        NaN
380           NaN             [ 월         계 ]        NaN
381           NaN             [ 누         계 ]        NaN

           계   정   별   원   장  Unnamed: 4  Unnamed: 5         Unnamed: 6
0    2018.01.01 ~ 2018.12.31         NaN         NaN                NaN
1                        NaN         NaN         NaN  계정과목 : [404] 제품매출
2                        거래처       차   변       대   변              잔   액
3            (주)히타치터미널-(주)씨텍         NaN    11820000           11820000
4                      실리콘일렉         NaN      810000           12630000
..                       ...         ...         ...                ...
377                (주)대한가스기기         NaN    10978800         7523060011
378             (주)마이크로컨텍솔루션         NaN   153160000         7676220011
379                      NaN  7676220011         NaN                NaN
380                      NaN  7676220011   924431200                NaN
381                      NaN  7676220011  7676220011                NaN

[382 rows x 7 columns]
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2018.01.01 ~ 2018.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3          01-15                임대료      02866                국일도어테크(주)
4          01-15               수도요금      02866                국일도어테크(주)
..           ...                ...        ...                      ...
56         12-31                임대료      03351                  슈텍E.N.G
57         12-31               수도요금      03351                  슈텍E.N.G
58         12-31           손익계정에 대체        NaN                      NaN
59           NaN    [ 월         계 ]        NaN                      NaN
60           NaN    [ 누         계 ]        NaN                      NaN

   Unnamed: 4 Unnamed: 5          Unnamed: 6
0         NaN        NaN                 NaN
1         NaN        NaN  계정과목 : [411] 임대료수입
2       차   변      대   변               잔   액
3         NaN     540000              540000
4         NaN      31650              571650

6   90874254   90874254                  NaN
     Unnamed: 0         Unnamed: 1 Unnamed: 2               계   정   별   원   장  \
0           NaN                NaN        NaN         2019.01.01 ~ 2019.12.31
1  회사명:(주)위너에코텍                NaN        NaN                             NaN
2            날짜        적    요    란         코드                             거래처
3           NaN               전기이월        NaN                             NaN
4         03-25         $34,309.93      03114  P O S COMMERCIAL CORPORATION C
5           NaN    [ 월         계 ]        NaN                             NaN
6           NaN    [ 누         계 ]        NaN                             NaN

  Unnamed: 4 Unnamed: 5          Unnamed: 6
0        NaN        NaN                 NaN
1        NaN        NaN  계정과목 : [979] 수입보증금
2      차   변      대   변               잔   액
3   37374677        NaN            37374677
4        NaN   37374677                 NaN
5        NaN   37374677                 NaN
6   37374677   37374677                 NaN
     Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0           NaN                NaN        NaN  2019.01.01 ~ 2019.12.31
1  회사명:(주)위너에코텍                NaN        NaN                      NaN
2            날짜        적    요    란         코드                      거래처
3         12-31         당기 미지급분 계상        NaN                      NaN
4         12-31           손익계정에 대체        NaN                      NaN
5           NaN    [ 월         계 ]        NaN                      NaN
6           NaN    [ 누         계 ]        NaN                      NaN

  Unnamed: 4 Unnamed: 5         Unnamed: 6
0        NaN        NaN                NaN
1        NaN        NaN  계정과목 : [998] 법인세등
2      차   변      대   변              잔   액
3   76963466        NaN           76963466
4        NaN   76963466                NaN
5   76963466   76963466                NaN
6   76963466   76963466                NaN
        Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0              NaN                NaN        NaN  2020.01.01 ~ 2020.12.31
1     회사명:(주)위너에코텍                NaN        NaN                      NaN
2               날짜        적    요    란         코드                      거래처
3              NaN               전기이월        NaN                      NaN
4            01-01            전기이월 수정      98160     기업 185-143782-01-017
...            ...                ...        ...                      ...
3252         12-31               이스턴빌      98003     기업 185-098540-04-029
3253         12-31              ２４시황궁      98003     기업 185-098540-04-029
3254         12-31              현대캐피탈      98003     기업 185-098540-04-029
3255           NaN    [ 월         계 ]        NaN                      NaN
3256           NaN    [ 누         계 ]        NaN                      NaN

       Unnamed: 4   Unnamed: 5         Unnamed: 6
0             NaN          NaN                NaN
1             NaN          NaN  계정과목 : [103] 보통예금
2           차   변        대   변              잔   액
3       657063480          NaN          657063480
4             830          NaN          657064310
...           ...          ...                ...
3252          NaN        67100          901033487
3253          NaN        69000          900964487
3254          NaN      1415947          899548540
3255   2892059012   2419294751                NaN
3256  32576482838  31676934298                NaN

[3257 rows x 7 columns]
       Unnamed: 0            Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0             NaN                   NaN        NaN  2020.01.01 ~ 2020.12.31
1    회사명:(주)위너에코텍                   NaN        NaN                      NaN
2              날짜           적    요    란         코드                      거래처
3             NaN                  전기이월        NaN                      NaN
4           01-01  $1,485.00 * 1,157.80      03106     RJR TECHNOLOGIES INC
..            ...                   ...        ...                      ...
682         12-31             외상매출금의 대손      00261    (주)로케트전기/2016.04.20폐업
683         12-31             외상매출금의 대손      01212      （주）티라인/2017.03.21폐업
684         12-31             외상매출금의 대손      02243   (주)테라마이크론/2019.05.09폐업
685           NaN       [ 월         계 ]        NaN                      NaN
686           NaN       [ 누         계 ]        NaN                      NaN

      Unnamed: 4   Unnamed: 5          Unnamed: 6
0            NaN          NaN                 NaN
1            NaN          NaN  계정과목 : [108] 외상매출금
2          차   변        대   변               잔   액
3     2654822646          NaN          2654822646
4        1719333          NaN          2656541979
..           ...          ...                 ...
682          NaN      1305150          1877159354
683          NaN     55000000          1822159354
684          NaN      2750000          1819409354
685   1103861478   1374726557                 NaN
686  20183728687  18364319333                 NaN

[687 rows x 7 columns]
     Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0           NaN                NaN        NaN  2020.01.01 ~ 2020.12.31
1  회사명:(주)위너에코텍                NaN        NaN                      NaN
2            날짜        적    요    란         코드                      거래처
3           NaN               전기이월        NaN                      NaN
4         01-01           대손충당금 환입        NaN                      NaN
5           NaN    [ 월         계 ]        NaN                      NaN
6           NaN    [ 누         계 ]        NaN                      NaN
7         12-31          외상매출금의 대손        NaN                      NaN
8           NaN    [ 월         계 ]        NaN                      NaN
9           NaN    [ 누         계 ]        NaN                      NaN

  Unnamed: 4 Unnamed: 5          Unnamed: 6
0        NaN        NaN                 NaN
1        NaN        NaN  계정과목 : [109] 대손충당금
2      차   변      대   변               잔   액
3        NaN   26548226            26548226
4   26548226        NaN                 NaN
5   26548226        NaN                 NaN
6   26548226   26548226                 NaN
7        NaN   18194093            18194093
8        NaN   18194093                 NaN
9   26548226   44742319                 NaN
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2020.01.01 ~ 2020.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3            NaN               전기이월        NaN                      NaN
4          01-01         ALG 시스템 대표      03561      ALG SYSTEM CO.,LTD.
5          01-01           대여금으로 대체      01377                 (주)화성커넥터
6          01-01           대여금으로 대체      00503                한승구-->김병수
7          01-01                 대체      02859                      나광원
8          01-01          가지급금으로 대체      01241                   김대수사장님
9          01-01                 대체      00358                      한수정
10         01-01         ALG 시스템 대표      03685                      이원호
11         01-31                최영철      03864                      최영철
12           NaN    [ 월         계 ]        NaN                      NaN
13           NaN    [ 누         계 ]        NaN                      NaN
14         05-15       기업하이젠월드　주식회사      03778               하이젠월드 주식회사
15           NaN    [ 월         계 ]        NaN                      NaN
16           NaN    [ 누         계 ]        NaN                      NaN
17         11-18                정윤용      01971                      정윤용
18         11-30           대출상환/정윤용      01971                      정윤용
19           NaN    [ 월         계 ]        NaN                      NaN
20           NaN    [ 누         계 ]        NaN                      NaN
21         12-14         （주）에이엘지시스템      03561      ALG SYSTEM CO.,LTD.
22         12-31          가지급금에서 대체      01241                   김대수사장님
23         12-31          가지급금에서 대체      00358                      한수정
24         12-31           대출상환/정윤용      01971                      정윤용
25           NaN    [ 월         계 ]        NaN                      NaN
26           NaN    [ 누         계 ]        NaN                      NaN

    Unnamed: 4 Unnamed: 5          Unnamed: 6
0          NaN        NaN                 NaN
1          NaN        NaN  계정과목 : [114] 단기대여금
2        차   변      대   변               잔   액
3   1357794084        NaN          1357794084
4      1000000        NaN          1358794084
5    100000000        NaN          1458794084
6     50000000        NaN          1508794084
7          NaN   12889300          1495904784
8          NaN   66372592          1429532192
9          NaN  219798593          1209733599
10         NaN    1000000          1208733599
11    10000000        NaN          1218733599
12   161000000  300060485                 NaN
13  1518794084  300060485                 NaN
14    50000000        NaN          1268733599
15    50000000        NaN                 NaN
16  1568794084  300060485                 NaN
17    67000000        NaN          1335733599
18         NaN     200000          1335533599
19    67000000     200000                 NaN
20  1635794084  300260485                 NaN
21    28000000        NaN          1363533599
22   472641392        NaN          1836174991
23   215683593        NaN          2051858584
24         NaN     200000          2051658584
25   716324985     200000                 NaN
26  2352119069  300460485                 NaN
       Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0             NaN                NaN        NaN  2020.01.01 ~ 2020.12.31
1    회사명:(주)위너에코텍                NaN        NaN                      NaN
2              날짜        적    요    란         코드                      거래처
3             NaN               전기이월        NaN                      NaN
4           01-10          국일도어테크（주）      02866                국일도어테크(주)
..            ...                ...        ...                      ...
121         12-15               수도요금      02866                국일도어테크(주)
122         12-17                정희라      03581                      펫나라
123         12-31                임대료      03581                      펫나라
124           NaN    [ 월         계 ]        NaN                      NaN
125           NaN    [ 누         계 ]        NaN                      NaN

    Unnamed: 4 Unnamed: 5        Unnamed: 6
0          NaN        NaN               NaN
1          NaN        NaN  계정과목 : [120] 미수금
2        차   변      대   변             잔   액
3      2787670        NaN           2787670
4          NaN     924000           1863670
..         ...        ...               ...
121     140430        NaN           9534430
122        NaN    1210000           8324430
123    1210000        NaN           9534430
124    2274430    2306180               NaN
125   37194230   27659800               NaN

[126 rows x 7 columns]
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2020.01.01 ~ 2020.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3            NaN               전기이월        NaN                      NaN
4          01-01        반환이자분 상계 오류      02697                   원주기업도시
..           ...                ...        ...                      ...
75         12-31         선지급액 선급금대체      03774                (주)해인씨앤에스
76         12-31         선지급액 선급금대체      03943                   엠케이에이엘
77         12-31         선지급액 선급금대체      03578                      대성퀵
78           NaN    [ 월         계 ]        NaN                      NaN
79           NaN    [ 누         계 ]        NaN                      NaN

    Unnamed: 4  Unnamed: 5        Unnamed: 6
0          NaN         NaN               NaN
1          NaN         NaN  계정과목 : [131] 선급금
2        차   변       대   변             잔   액
3   1406154961         NaN        1406154961
4        22800         NaN        1406177761
..         ...         ...               ...
75     3817000         NaN        1058319934
76       27720         NaN        1058347654
77      117700         NaN        1058465354
78    36468657         NaN               NaN
79  2275489154  1217023800               NaN

[80 rows x 7 columns]
     Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0           NaN                NaN        NaN  2020.01.01 ~ 2020.12.31
1  회사명:(주)위너에코텍                NaN        NaN                      NaN
2            날짜        적    요    란         코드                      거래처
3           NaN               전기이월        NaN                      NaN
4         01-01       선급보험료의 재수정분개        NaN                      NaN
5           NaN    [ 월         계 ]        NaN                      NaN
6           NaN    [ 누         계 ]        NaN                      NaN
7         12-31        보험료의 선급비용대체        NaN                      NaN
8           NaN    [ 월         계 ]        NaN                      NaN
9           NaN    [ 누         계 ]        NaN                      NaN

  Unnamed: 4 Unnamed: 5         Unnamed: 6
0        NaN        NaN                NaN
1        NaN        NaN  계정과목 : [133] 선급비용
2      차   변      대   변              잔   액
3    8001784        NaN            8001784
4        NaN    8001784                NaN
5        NaN    8001784                NaN
6    8001784    8001784                NaN
7   10459256        NaN           10459256
8   10459256        NaN                NaN
9   18461040    8001784                NaN
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2020.01.01 ~ 2020.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3          01-01       단기채권에서대체(법인)      01241                   김대수사장님
4          01-01       가지급금 단기채권 대체      00358                      한수정
5          01-01       단기채권에서대체(법인)      01241                   김대수사장님
6          01-01             가지급금회수      01241                   김대수사장님
7          01-07       단기채권으로대체(법인)      01241                   김대수사장님
8          01-07       가지급금 단기채권 대체      00358                      한수정
9          01-15       가지급금 단기채권 대체      00358                      한수정
10         01-17       단기채권에서대체(법인)      01241                   김대수사장님
11         01-22       단기채권에서대체(법인)      01241                   김대수사장님
12         01-31       단기채권으로대체(법인)      01241                   김대수사장님
13           NaN    [ 월         계 ]        NaN                      NaN
14           NaN    [ 누         계 ]        NaN                      NaN
15         06-01       단기채권에서대체(법인)      01241                   김대수사장님
16           NaN    [ 월         계 ]        NaN                      NaN
17           NaN    [ 누         계 ]        NaN                      NaN
18         08-05       단기채권에서대체(법인)      01241                   김대수사장님
19           NaN    [ 월         계 ]        NaN                      NaN
20           NaN    [ 누         계 ]        NaN                      NaN
21         12-29          임시가지급(법인)      01241                   김대수사장님
22         12-31       단기채권으로대체(법인)      01241                   김대수사장님
23         12-31       가지급금 단기채권 대체      00358                      한수정
24           NaN    [ 월         계 ]        NaN                      NaN
25           NaN    [ 누         계 ]        NaN                      NaN

   Unnamed: 4 Unnamed: 5         Unnamed: 6
0         NaN        NaN                NaN
1         NaN        NaN  계정과목 : [134] 가지급금
2       차   변      대   변              잔   액
3    66372592        NaN           66372592
4   219798593        NaN          286171185
5   255000000        NaN          541171185
6         NaN    2000000          539171185
7         NaN   20000000          519171185
8         NaN    2000000          517171185
9         NaN    2115000          515056185
10    5000000        NaN          520056185
11  100000000        NaN          620056185
12        NaN    3731200          616324985
13  646171185   29846200                NaN
14  646171185   29846200                NaN
15   50000000        NaN          666324985
16   50000000        NaN                NaN
17  696171185   29846200                NaN
18   20000000        NaN          686324985
19   20000000        NaN                NaN
20  716171185   29846200                NaN
21    2000000        NaN          688324985
22        NaN  472641392          215683593
23        NaN  215683593                NaN
24    2000000  688324985                NaN
25  718171185  718171185                NaN
        Unnamed: 0                           Unnamed: 1 Unnamed: 2  \
0              NaN                                  NaN        NaN
1     회사명:(주)위너에코텍                                  NaN        NaN
2               날짜                          적    요    란         코드
3            01-01   서비스료(20200201~20200229) 1 X 80,000      00217
4            01-01  서비스료(20200201~20200229) 1 X 125,000      00217
...            ...                                  ...        ...
2695         12-31                                  임대료      02582
2696         12-31                         세븐일레븐 군포금정동점      03807
2697         12-31                           부가세예수금과 상계        NaN
2698           NaN                      [ 월         계 ]        NaN
2699           NaN                      [ 누         계 ]        NaN

            계   정   별   원   장  Unnamed: 4  Unnamed: 5           Unnamed: 6
0     2020.01.01 ~ 2020.12.31         NaN         NaN                  NaN
1                         NaN         NaN         NaN  계정과목 : [135] 부가세대급금
2                         거래처       차   변       대   변                잔   액
3                   (주)에스원 안양        8000         NaN                 8000
4                   (주)에스원 안양       12500         NaN                20500
...                       ...         ...         ...                  ...
2695            한수정(수촌리159-3)      600000         NaN            263540530
2696             세븐일레븐 군포금정동점        3629         NaN            263544159
2697                      NaN         NaN   263544159                  NaN
2698                      NaN    53012936   263544159                  NaN
2699                      NaN  1239114243  1239114243                  NaN

[2700 rows x 7 columns]
      Unnamed: 0                  Unnamed: 1 Unnamed: 2  \
0            NaN                         NaN        NaN
1   회사명:(주)위너에코텍                         NaN        NaN
2             날짜                 적    요    란         코드
3          03-17                계좌해지시 이자세금납부      00157
4          03-17                계좌해지시 이자세금납부      03217
5          03-29           $13.82 * 1,227.90      00157
6          03-29           $13.82 * 1,227.90      03217
7            NaN             [ 월         계 ]        NaN
8            NaN             [ 누         계 ]        NaN
9          06-28  2020년 결산 $14.66 * 1,205.20      00157
10         06-28  2020년 결산 $14.66 * 1,205.20      03217
11         06-30                     신탁 원가결산      00157
12         06-30                         NaN      03217
13           NaN             [ 월         계 ]        NaN
14           NaN             [ 누         계 ]        NaN
15         09-08            14-001계좌해지 이자소득세      00157
16         09-08          14-001계좌해지 이자지방소득세      03217
17         09-21                     2020년결산      00157
18         09-21                         NaN      03217
19         09-27  2020년 결산 $36.51 * 1,170.30      00157
20         09-27  2020년 결산 $36.51 * 1,170.30      03217
21         09-29                     신탁 원가결산      00157
22         09-29                     신탁 원가결산      03217
23           NaN             [ 월         계 ]        NaN

[86 rows x 7 columns]
       Unnamed: 0                                   Unnamed: 1 Unnamed: 2  \
0             NaN                                          NaN        NaN
1    회사명:(주)위너에코텍                                          NaN        NaN
2              날짜                                  적    요    란         코드
3           01-02               3792 [0106]59호3792 맥시마 (1.유류비)      17638
4           01-02       아반떼 2025 유류대 [0104]48하2025 아반떼 (1.유류비)      00762
..            ...                                          ...        ...
265         12-30           그랜저 유류대 [0115]104허7345 그랜저 (1.유류비)      01104
266         12-31  동일석유(주)산업주유소 그랜저 [0115]104허7345 그랜저 (1.유류비)      00668
267         12-31                                     손익계정에 대체        NaN
268           NaN                              [ 월         계 ]        NaN
269           NaN                              [ 누         계 ]        NaN

           계   정   별   원   장 Unnamed: 4 Unnamed: 5          Unnamed: 6
0    2020.01.01 ~ 2020.12.31        NaN        NaN                 NaN
1                        NaN        NaN        NaN  계정과목 : [822] 차량유지비
2                        거래처      차   변      대   변               잔   액
3                     싸이클주유소      70000        NaN               70000
4                 배양에너지 주식회사      50000        NaN              120000
..                       ...        ...        ...                 ...
265         현대오일뱅크（주）직영우신주유소      50000        NaN            17583623
266             동일석유(주)산업주유소      50000        NaN            17633623
267                      NaN        NaN   17633623                 NaN
268                      NaN    1612500   17633623                 NaN
269                      NaN   17633623   17633623                 NaN

[270 rows x 7 columns]
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2020.01.01 ~ 2020.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3          01-31              급여등지급        NaN                      NaN
4            NaN    [ 월         계 ]        NaN                      NaN
5            NaN    [ 누         계 ]        NaN                      NaN
6          02-28              급여등지급        NaN                      NaN
7            NaN    [ 월         계 ]        NaN                      NaN
8            NaN    [ 누         계 ]        NaN                      NaN
9          03-31              급여등지급        NaN                      NaN
10           NaN    [ 월         계 ]        NaN                      NaN
11           NaN    [ 누         계 ]        NaN                      NaN
12         04-30              급여등지급        NaN                      NaN
13           NaN    [ 월         계 ]        NaN                      NaN
14           NaN    [ 누         계 ]        NaN                      NaN
15         05-31              급여등지급        NaN                      NaN
16           NaN    [ 월         계 ]        NaN                      NaN
17           NaN    [ 누         계 ]        NaN                      NaN
18         06-30              급여등지급        NaN                      NaN
19           NaN    [ 월         계 ]        NaN                      NaN
20           NaN    [ 누         계 ]        NaN                      NaN
21         07-31              급여등지급        NaN                      NaN
22           NaN    [ 월         계 ]        NaN                      NaN
23           NaN    [ 누         계 ]        NaN                      NaN
24         08-31              급여등지급        NaN                      NaN
25           NaN    [ 월         계 ]        NaN                      NaN
26           NaN    [ 누         계 ]        NaN                      NaN
27         09-30              급여등지급        NaN                      NaN
28           NaN    [ 월         계 ]        NaN                      NaN
29           NaN    [ 누         계 ]        NaN                      NaN
30         10-31              급여등지급        NaN                      NaN
31           NaN    [ 월         계 ]        NaN                      NaN
32           NaN    [ 누         계 ]        NaN                      NaN
33         11-30              급여등지급        NaN                      NaN
34           NaN    [ 월         계 ]        NaN                      NaN
35           NaN    [ 누         계 ]        NaN                      NaN
36         12-31              급여등지급        NaN                      NaN
37         12-31          급여등지급 성과급        NaN                      NaN
38         12-31  개발비 연구중단으로 단기비용처리        NaN                      NaN
39         12-31           손익계정에 대체        NaN                      NaN
40           NaN    [ 월         계 ]        NaN                      NaN
41           NaN    [ 누         계 ]        NaN                      NaN

   Unnamed: 4 Unnamed: 5            Unnamed: 6
0         NaN        NaN                   NaN
1         NaN        NaN  계정과목 : [823] 경상연구개발비
2       차   변      대   변                 잔   액
3    13449880        NaN              13449880
4    13449880        NaN                   NaN
5    13449880        NaN                   NaN
6    11070730        NaN              24520610
7    11070730        NaN                   NaN
8    24520610        NaN                   NaN
9    13550160        NaN              38070770
10   13550160        NaN                   NaN
11   38070770        NaN                   NaN
12   12607570        NaN              50678340
13   12607570        NaN                   NaN
14   50678340        NaN                   NaN
15   14771010        NaN              65449350
16   14771010        NaN                   NaN
17   65449350        NaN                   NaN
18   14131480        NaN              79580830
19   14131480        NaN                   NaN
20   79580830        NaN                   NaN
21   15320240        NaN              94901070
22   15320240        NaN                   NaN
23   94901070        NaN                   NaN
24   13349860        NaN             108250930
25   13349860        NaN                   NaN
26  108250930        NaN                   NaN
27   15405320        NaN             123656250
28   15405320        NaN                   NaN
29  123656250        NaN                   NaN
30   13339230        NaN             136995480
31   13339230        NaN                   NaN
32  136995480        NaN                   NaN
33   13328590        NaN             150324070
34   13328590        NaN                   NaN
35  150324070        NaN                   NaN
36   15671200        NaN             165995270
37    2500000        NaN             168495270
38  107259030        NaN             275754300
39        NaN  275754300                   NaN
40  125430230  275754300                   NaN
41  275754300  275754300                   NaN
      Unnamed: 0                                         Unnamed: 1  \
0            NaN                                                NaN
1   회사명:(주)위너에코텍                                                NaN
2             날짜                                        적    요    란
3          03-09                                  안전보건교육 1 X 59,000
4            NaN                                    [ 월         계 ]
5            NaN                                    [ 누         계 ]
6          07-22  제2차 수소에너지 인프라 구축과 연계산업 및 사업모델 최신분석 세미나 1 X 400...
7            NaN                                    [ 월         계 ]
8            NaN                                    [ 누         계 ]
9          12-31                                           손익계정에 대체
10           NaN                                    [ 월         계 ]
11           NaN                                    [ 누         계 ]

   Unnamed: 2        계   정   별   원   장 Unnamed: 4 Unnamed: 5  \
0         NaN  2020.01.01 ~ 2020.12.31        NaN        NaN
1         NaN                      NaN        NaN        NaN
2          코드                      거래처      차   변      대   변
3       02418            사단법인 대한안전교육협회      59000        NaN
4         NaN                      NaN      59000        NaN
5         NaN                      NaN      59000        NaN
6       01884                  산업교육연구소     400000        NaN
7         NaN                      NaN     400000        NaN
8         NaN                      NaN     459000        NaN
9         NaN                      NaN        NaN     459000
10        NaN                      NaN        NaN     459000
11        NaN                      NaN     459000     459000

            Unnamed: 6
0                  NaN
1   계정과목 : [825] 교육훈련비
2                잔   액
3                59000
4                  NaN
5                  NaN
6               459000
7                  NaN
8                  NaN
9                  NaN
10                 NaN
11                 NaN
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2020.01.01 ~ 2020.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3          01-02               매일경제        NaN                      NaN
4            NaN    [ 월         계 ]        NaN                      NaN
5            NaN    [ 누         계 ]        NaN                      NaN
6          04-18            (주)교보문고        NaN                  （주）교보문고
7          04-23            (주)교보문고        NaN                  （주）교보문고
8            NaN    [ 월         계 ]        NaN                      NaN
9            NaN    [ 누         계 ]        NaN                      NaN
10         11-02               매일경제        NaN                      NaN
11           NaN    [ 월         계 ]        NaN                      NaN
12           NaN    [ 누         계 ]        NaN                      NaN
13         12-31           손익계정에 대체        NaN                      NaN
14           NaN    [ 월         계 ]        NaN                      NaN
15           NaN    [ 누         계 ]        NaN                      NaN

   Unnamed: 4 Unnamed: 5          Unnamed: 6
0         NaN        NaN                 NaN
1         NaN        NaN  계정과목 : [826] 도서인쇄비
2       차   변      대   변               잔   액
3      200000        NaN              200000
4      200000        NaN                 NaN
5      200000        NaN                 NaN
6        6900        NaN              206900
7       24000        NaN              230900
8       30900        NaN                 NaN
9      230900        NaN                 NaN
10     200000        NaN              430900
11     200000        NaN                 NaN
12     430900        NaN                 NaN
13        NaN     430900                 NaN
14        NaN     430900                 NaN
15     430900     430900                 NaN
      Unnamed: 0                  Unnamed: 1 Unnamed: 2  \
0            NaN                         NaN        NaN
1   회사명:(주)위너에코텍                         NaN        NaN
2             날짜                 적    요    란         코드
3          01-06  거래명세표(신형) 1000매 2 X 30,000      00279
4          01-10  거래명세표(구형) 1000매 1 X 30,000      00279
..           ...                         ...        ...
62         12-30                       모닝글로리      02986
63         12-31            사무용품외 1 X 55,180      01634
64         12-31                    손익계정에 대체        NaN
65           NaN             [ 월         계 ]        NaN
66           NaN             [ 누         계 ]        NaN

          계   정   별   원   장 Unnamed: 4 Unnamed: 5          Unnamed: 6
0   2020.01.01 ~ 2020.12.31        NaN        NaN                 NaN
1                       NaN        NaN        NaN  계정과목 : [829] 사무용품비
2                       거래처      차   변      대   변               잔   액
3                  (주)아이퀘스트      60000        NaN               60000
4                  (주)아이퀘스트      30000        NaN               90000
..                      ...        ...        ...                 ...
62                    모닝글로리      12818        NaN             4132913
63                 드림디포 금정점      50164        NaN             4183077
64                      NaN        NaN    4183077                 NaN
65                      NaN     262982    4183077                 NaN
66                      NaN    4183077    4183077                 NaN

[67 rows x 7 columns]
       Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0             NaN                NaN        NaN  2020.01.01 ~ 2020.12.31
1    회사명:(주)위너에코텍                NaN        NaN                      NaN
2              날짜        적    요    란         코드                      거래처
3           01-06           카드 - 소모품      03666             네이버파이낸셜 주식회사
4           01-06           카드 - 소모품      03666             네이버파이낸셜 주식회사
..            ...                ...        ...                      ...
249         12-30            홈플러스안양점        NaN                  홈플러스안양점
250         12-31              석소편의점        NaN                    석소편의점
251         12-31           손익계정에 대체        NaN                      NaN
252           NaN    [ 월         계 ]        NaN                      NaN
253           NaN    [ 누         계 ]        NaN                      NaN

    Unnamed: 4 Unnamed: 5         Unnamed: 6
0          NaN        NaN                NaN
1          NaN        NaN  계정과목 : [830] 소모품비
2        차   변      대   변              잔   액
3        12637        NaN              12637
4        18064        NaN              30701
..         ...        ...                ...
249      14000        NaN           25933786
250       6000        NaN           25939786
251        NaN   25939786                NaN
252    3133578   25939786                NaN
253   25939786   25939786                NaN

[254 rows x 7 columns]
       Unnamed: 0                           Unnamed: 1 Unnamed: 2  \
0             NaN                                  NaN        NaN
1    회사명:(주)위너에코텍                                  NaN        NaN
2              날짜                          적    요    란         코드
3           01-01   서비스료(20200201~20200229) 1 X 80,000      00217
4           01-01  서비스료(20200201~20200229) 1 X 125,000      00217
..            ...                                  ...        ...
408         12-31                                  NaN      03904
409         12-31                                할부수수료        NaN
410         12-31                             손익계정에 대체        NaN
411           NaN                      [ 월         계 ]        NaN
412           NaN                      [ 누         계 ]        NaN

                  계   정   별   원   장 Unnamed: 4 Unnamed: 5          Unnamed: 6
0           2020.01.01 ~ 2020.12.31        NaN        NaN                 NaN
1                               NaN        NaN        NaN  계정과목 : [831] 지급수수료
2                               거래처      차   변      대   변               잔   액
3                         (주)에스원 안양      80000        NaN               80000
4                         (주)에스원 안양     125000        NaN              205000
..                              ...        ...        ...                 ...
408  SENSATA TECHNOLOGIES CHANGZHOU      15000        NaN            56259791
409                         평촌현대모터스      10948        NaN            56270739
410                             NaN        NaN   56270739                 NaN
411                             NaN    3827834   56270739                 NaN
412                             NaN   56270739   56270739                 NaN

[413 rows x 7 columns]
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2020.01.01 ~ 2020.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3          12-31          외상매출금의 대손      00261    (주)로케트전기/2016.04.20폐업
4          12-31          외상매출금의 대손      01212      （주）티라인/2017.03.21폐업
5          12-31          외상매출금의 대손      02243   (주)테라마이크론/2019.05.09폐업
6          12-31          외상매출금의 대손      01523    주식회사 씨큐로/2019.03.15폐업
7          12-31          외상매출금의 대손        NaN                      NaN
8          12-31           손익계정에 대체        NaN                      NaN
9            NaN    [ 월         계 ]        NaN                      NaN
10           NaN    [ 누         계 ]        NaN                      NaN

   Unnamed: 4 Unnamed: 5          Unnamed: 6
0         NaN        NaN                 NaN
1         NaN        NaN  계정과목 : [835] 대손상각비
2       차   변      대   변               잔   액
3     1305150        NaN             1305150
4    55000000        NaN            56305150
5     2750000        NaN            59055150
6    16445000        NaN            75500150
7    18194093        NaN            93694243
8         NaN   93694243                 NaN
9    93694243   93694243                 NaN
10   93694243   93694243                 NaN
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2020.01.01 ~ 2020.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3          01-21                관리비      00234                리딩브레인/최종운
4            NaN    [ 월         계 ]        NaN                      NaN
5            NaN    [ 누         계 ]        NaN                      NaN
6          02-21                관리비      00234                리딩브레인/최종운
7            NaN    [ 월         계 ]        NaN                      NaN
8            NaN    [ 누         계 ]        NaN                      NaN
9          03-23                관리비      00234                리딩브레인/최종운
10           NaN    [ 월         계 ]        NaN                      NaN
11           NaN    [ 누         계 ]        NaN                      NaN
12         04-23                관리비      00234                리딩브레인/최종운
13           NaN    [ 월         계 ]        NaN                      NaN
14           NaN    [ 누         계 ]        NaN                      NaN
15         05-22                관리비      00234                리딩브레인/최종운
16           NaN    [ 월         계 ]        NaN                      NaN
17           NaN    [ 누         계 ]        NaN                      NaN
18         06-15       2020년 6월 관리비      03796     이스턴 빌 (EASTERN VILL)
19         06-23                관리비      00234                리딩브레인/최종운
20           NaN    [ 월         계 ]        NaN                      NaN
21           NaN    [ 누         계 ]        NaN                      NaN
22         07-23                관리비      00234                리딩브레인/최종운
23           NaN    [ 월         계 ]        NaN                      NaN
24           NaN    [ 누         계 ]        NaN                      NaN
25         08-04       2020년 7월 관리비      03796     이스턴 빌 (EASTERN VILL)
26         08-24                관리비      00234                리딩브레인/최종운
27           NaN    [ 월         계 ]        NaN                      NaN
28           NaN    [ 누         계 ]        NaN                      NaN
29         09-06       2020년 9월 관리비      03796     이스턴 빌 (EASTERN VILL)
30         09-06       2020년 8월 관리비      03796     이스턴 빌 (EASTERN VILL)
31         09-23                관리비      00234                리딩브레인/최종운
32           NaN    [ 월         계 ]        NaN                      NaN
33           NaN    [ 누         계 ]        NaN                      NaN
34         10-23                관리비      00234                리딩브레인/최종운
35           NaN    [ 월         계 ]        NaN                      NaN
36           NaN    [ 누         계 ]        NaN                      NaN
37         11-03      2020년 10월 관리비      03796     이스턴 빌 (EASTERN VILL)
38         11-23                관리비      00234                리딩브레인/최종운
39           NaN    [ 월         계 ]        NaN                      NaN

       Unnamed: 0                        Unnamed: 1 Unnamed: 2  \
0             NaN                               NaN        NaN
1    회사명:(주)위너에코텍                               NaN        NaN
2              날짜                       적    요    란         코드
3           01-04                              물품대금      00176
4           01-07  ASM_AUTO(몰렉스/6PIN/연결잭) 7 X 7,060      03492
..            ...                               ...        ...
459         12-31                              물품대금      00186
460         12-31                              금형대금      00178
461         12-31                          손익계정에 대체        NaN
462           NaN                   [ 월         계 ]        NaN
463           NaN                   [ 누         계 ]        NaN

           계   정   별   원   장   Unnamed: 4   Unnamed: 5         Unnamed: 6
0    2021.01.01 ~ 2021.12.31          NaN          NaN                NaN
1                        NaN          NaN          NaN  계정과목 : [404] 제품매출
2                        거래처        차   변        대   변              잔   액
3                     (주)포스텔          NaN     19157080           19157080
4                   주식회사 포피스          NaN       136930           19294010
..                       ...          ...          ...                ...
459                 (주)오킨스전자          NaN     22964350        18867319895
460             (주)마이크로컨텍솔루션          NaN    428200000        19295519895
461                      NaN  19295519895          NaN                NaN
462                      NaN  19295519895   1622139270                NaN
463                      NaN  19295519895  19295519895                NaN

[464 rows x 7 columns]
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2021.01.01 ~ 2021.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3          01-15                임대료      02866                국일도어테크(주)
4          01-15               수도요금      02866                국일도어테크(주)
5          01-31                임대료      03581                      펫나라
6            NaN    [ 월         계 ]        NaN                      NaN
7            NaN    [ 누         계 ]        NaN                      NaN
8          02-15                임대료      02866                국일도어테크(주)
9          02-15               수도요금      02866                국일도어테크(주)
10         02-28                임대료      03581                      펫나라
11           NaN    [ 월         계 ]        NaN                      NaN
12           NaN    [ 누         계 ]        NaN                      NaN
13         03-15                임대료      02866                국일도어테크(주)
14         03-15               수도요금      02866                국일도어테크(주)
15         03-31                임대료      03581                      펫나라
16           NaN    [ 월         계 ]        NaN                      NaN
17           NaN    [ 누         계 ]        NaN                      NaN
18         04-15                임대료      02866                국일도어테크(주)
19         04-15               수도요금      02866                국일도어테크(주)
20         04-30                임대료      03581                      펫나라
21           NaN    [ 월         계 ]        NaN                      NaN
22           NaN    [ 누         계 ]        NaN                      NaN
23         05-31                임대료      03581                      펫나라
24         05-31                임대료      02866                국일도어테크(주)
25         05-31               수도요금      02866                국일도어테크(주)
26           NaN    [ 월         계 ]        NaN                      NaN
27           NaN    [ 누         계 ]        NaN                      NaN
28         06-30                임대료      03581                      펫나라
29         06-30                임대료      02866                국일도어테크(주)
30         06-30               수도요금      02866                국일도어테크(주)
31           NaN    [ 월         계 ]        NaN                      NaN
32           NaN    [ 누         계 ]        NaN                      NaN
33         07-31                임대료      03581                      펫나라
34         07-31                임대료      02866                국일도어테크(주)
35         07-31               수도요금      02866                국일도어테크(주)
36           NaN    [ 월         계 ]        NaN                      NaN
37           NaN    [ 누         계 ]        NaN                      NaN
38         08-07                임대료      02866                국일도어테크(주)
39         08-07               수도요금      02866                국일도어테크(주)
40         08-31                임대료      03581                      펫나라
41           NaN    [ 월         계 ]        NaN                      NaN
42           NaN    [ 누         계 ]        NaN                      NaN
43         09-30                임대료      03581                      펫나라
44           NaN    [ 월         계 ]        NaN                      NaN
45           NaN    [ 누         계 ]        NaN                      NaN
46         10-31                임대료      03581                      펫나라
47           NaN    [ 월         계 ]        NaN                      NaN
48           NaN    [ 누         계 ]        NaN                      NaN
49         11-30                임대료      03581                      펫나라
50           NaN    [ 월         계 ]        NaN                      NaN
51           NaN    [ 누         계 ]        NaN                      NaN
52         12-31                임대료      03581                      펫나라
53         12-31           손익계정에 대체        NaN                      NaN
54           NaN    [ 월         계 ]        NaN                      NaN
55           NaN    [ 누         계 ]        NaN                      NaN

   Unnamed: 4 Unnamed: 5          Unnamed: 6
0         NaN        NaN                 NaN
1         NaN        NaN  계정과목 : [411] 임대료수입
2       차   변      대   변               잔   액
3         NaN     840000              840000
4         NaN     111200              951200
5         NaN    1100000             2051200
6         NaN    2051200                 NaN
7         NaN    2051200                 NaN
8         NaN     840000             2891200
9         NaN     166150             3057350
10        NaN    1100000             4157350
11        NaN    2106150                 NaN
12        NaN    4157350                 NaN
13        NaN     840000             4997350
14        NaN     115650             5113000
15        NaN    1100000             6213000
16        NaN    2055650                 NaN
17        NaN    6213000                 NaN
18        NaN     840000             7053000
19        NaN     125230             7178230
20        NaN    1100000             8278230
21        NaN    2065230                 NaN
22        NaN    8278230                 NaN
23        NaN    1100000             9378230
24        NaN     840000            10218230
25        NaN     141600            10359830
26        NaN    2081600                 NaN
27        NaN   10359830                 NaN
28        NaN    1100000            11459830
29        NaN     840000            12299830
30        NaN     113690            12413520
31        NaN    2053690                 NaN
32        NaN   12413520                 NaN
33        NaN    1100000            13513520
34        NaN     840000            14353520
35        NaN     108860            14462380
36        NaN    2048860                 NaN
37        NaN   14462380                 NaN
38        NaN     189670            14652050
39        NaN      24580            14676630
40        NaN    1100000            15776630
41        NaN    1314250                 NaN
42        NaN   15776630                 NaN
43        NaN    1100000            16876630
44        NaN    1100000                 NaN
45        NaN   16876630                 NaN
46        NaN    1100000            17976630
47        NaN    1100000                 NaN
48        NaN   17976630                 NaN
49        NaN    1100000            19076630
50        NaN    1100000                 NaN
51        NaN   19076630                 NaN
52        NaN    1100000            20176630
53   20176630        NaN                 NaN
54   20176630    1100000                 NaN
55   20176630   20176630                 NaN
       Unnamed: 0         Unnamed: 1 Unnamed: 2  \
0             NaN                NaN        NaN
1    회사명:(주)위너에코텍                NaN        NaN
2              날짜        적    요    란         코드
3           01-01           \950,000      03904
4           01-05         \5,508,500      03904
..            ...                ...        ...
175         12-24         \6,000,000      03904
176         12-29         \3,964,000      03904
177         12-31           손익계정에 대체        NaN
178           NaN    [ 월         계 ]        NaN
179           NaN    [ 누         계 ]        NaN

                  계   정   별   원   장  Unnamed: 4  Unnamed: 5         Unnamed: 6
0           2021.01.01 ~ 2021.12.31         NaN         NaN                NaN
1                               NaN         NaN         NaN  계정과목 : [413] 수출매출
2                               거래처       차   변       대   변              잔   액
3    SENSATA TECHNOLOGIES CHANGZHOU         NaN      950000             950000
4    SENSATA TECHNOLOGIES CHANGZHOU         NaN     5508500            6458500
..                              ...         ...         ...                ...
175  SENSATA TECHNOLOGIES CHANGZHOU         NaN     6000000         1032568596
176  SENSATA TECHNOLOGIES CHANGZHOU         NaN     3964000         1036532596
177                             NaN  1036532596         NaN                NaN
178                             NaN  1036532596   114483500                NaN
179                             NaN  1036532596  1036532596                NaN

[180 rows x 7 columns]
     Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0           NaN                NaN        NaN  2021.01.01 ~ 2021.12.31
1  회사명:(주)위너에코텍                NaN        NaN                      NaN
2            날짜        적    요    란         코드                      거래처
3         12-31          제품매출원가 대체        NaN                      NaN
4         12-31           손익계정에 대체        NaN                      NaN
5           NaN    [ 월         계 ]        NaN                      NaN
6           NaN    [ 누         계 ]        NaN                      NaN

    Unnamed: 4   Unnamed: 5           Unnamed: 6
0          NaN          NaN                  NaN
1          NaN          NaN  계정과목 : [455] 제품매출원가
2        차   변        대   변                잔   액
3  13663835689          NaN          13663835689
4          NaN  13663835689                  NaN
5  13663835689  13663835689                  NaN
6  13663835689  13663835689                  NaN
     Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0           NaN                NaN        NaN  2021.01.01 ~ 2021.12.31
1  회사명:(주)위너에코텍                NaN        NaN                      NaN
2            날짜        적    요    란         코드                      거래처
3         12-31       원재료사용분 재료비대체        NaN                      NaN
4         12-31         재료비 제조로 대체        NaN                      NaN
5           NaN    [ 월         계 ]        NaN                      NaN
6           NaN    [ 누         계 ]        NaN                      NaN

   Unnamed: 4  Unnamed: 5         Unnamed: 6
0         NaN         NaN                NaN
1         NaN         NaN  계정과목 : [501] 원재료비
2       차   변       대   변              잔   액
3  6883718211         NaN         6883718211
4         NaN  6883718211                NaN
5  6883718211  6883718211                NaN
6  6883718211  6883718211                NaN
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2021.01.01 ~ 2021.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3          01-31              급여등지급        NaN                      NaN
4            NaN    [ 월         계 ]        NaN                      NaN
5            NaN    [ 누         계 ]        NaN                      NaN
6          02-28              급여등지급        NaN                      NaN
7            NaN    [ 월         계 ]        NaN                      NaN
8            NaN    [ 누         계 ]        NaN                      NaN
9          03-31              급여등지급        NaN                      NaN
10           NaN    [ 월         계 ]        NaN                      NaN
11           NaN    [ 누         계 ]        NaN                      NaN
12         04-30              급여등지급        NaN                      NaN
13           NaN    [ 월         계 ]        NaN                      NaN
14           NaN    [ 누         계 ]        NaN                      NaN
15         05-31              급여등지급        NaN                      NaN
16           NaN    [ 월         계 ]        NaN                      NaN
17           NaN    [ 누         계 ]        NaN                      NaN
18         06-30              급여등지급        NaN                      NaN
19           NaN    [ 월         계 ]        NaN                      NaN
20           NaN    [ 누         계 ]        NaN                      NaN
21         07-31              급여등지급        NaN                      NaN
22           NaN    [ 월         계 ]        NaN                      NaN
23           NaN    [ 누         계 ]        NaN                      NaN
24         08-31              급여등지급        NaN                      NaN
25           NaN    [ 월         계 ]        NaN                      NaN
26           NaN    [ 누         계 ]        NaN                      NaN
27         09-30              급여등지급        NaN                      NaN
28           NaN    [ 월         계 ]        NaN                      NaN
29           NaN    [ 누         계 ]        NaN                      NaN
30         10-31              급여등지급        NaN                      NaN
31           NaN    [ 월         계 ]        NaN                      NaN
32           NaN    [ 누         계 ]        NaN                      NaN
33         11-30              급여등지급        NaN                      NaN
34           NaN    [ 월         계 ]        NaN                      NaN
35           NaN    [ 누         계 ]        NaN                      NaN
36         12-31              급여등지급        NaN                      NaN
37         12-31             제조로 대체        NaN                      NaN
38           NaN    [ 월         계 ]        NaN                      NaN
39           NaN    [ 누         계 ]        NaN                      NaN

    Unnamed: 4  Unnamed: 5       Unnamed: 6
0          NaN         NaN              NaN
1          NaN         NaN  계정과목 : [504] 임금
2        차   변       대   변            잔   액
3    104356560         NaN        104356560
4    104356560         NaN              NaN
5    104356560         NaN              NaN
6     95552790         NaN        199909350
7     95552790         NaN              NaN
8    199909350         NaN              NaN
9    104218530         NaN        304127880
10   104218530         NaN              NaN
11   304127880         NaN              NaN
12   109403610         NaN        413531490
13   109403610         NaN              NaN
14   413531490         NaN              NaN
15   107880630         NaN        521412120
16   107880630         NaN              NaN
17   521412120         NaN              NaN
18    96381170         NaN        617793290
19    96381170         NaN              NaN
20   617793290         NaN              NaN
21    92531080         NaN        710324370
22    92531080         NaN              NaN
23   710324370         NaN              NaN
24    92573050         NaN        802897420
25    92573050         NaN              NaN
26   802897420         NaN              NaN
27    92949550         NaN        895846970
28    92949550         NaN              NaN
29   895846970         NaN              NaN
30    93498760         NaN        989345730
31    93498760         NaN              NaN
32   989345730         NaN              NaN
33    84527830         NaN       1073873560
34    84527830         NaN              NaN
35  1073873560         NaN              NaN
36   126570910         NaN       1200444470
37         NaN  1200444470              NaN
38   126570910  1200444470              NaN
39  1200444470  1200444470              NaN
      Unnamed: 0         Unnamed: 1 Unnamed: 2        계   정   별   원   장  \
0            NaN                NaN        NaN  2021.01.01 ~ 2021.12.31
1   회사명:(주)위너에코텍                NaN        NaN                      NaN
2             날짜        적    요    란         코드                      거래처
3          02-28              급여등지급        NaN                      NaN
4            NaN    [ 월         계 ]        NaN                      NaN
5            NaN    [ 누         계 ]        NaN                      NaN
6          07-31              급여등지급        NaN                      NaN
7            NaN    [ 월         계 ]        NaN                      NaN
8            NaN    [ 누         계 ]        NaN                      NaN
9          09-30              급여등지급        NaN                      NaN
10           NaN    [ 월         계 ]        NaN                      NaN
11           NaN    [ 누         계 ]        NaN                      NaN
12         12-31              급여등지급        NaN                      NaN
13         12-31             제조로 대체        NaN                      NaN
14           NaN    [ 월         계 ]        NaN                      NaN
15           NaN    [ 누         계 ]        NaN                      NaN

   Unnamed: 4 Unnamed: 5        Unnamed: 6
0         NaN        NaN               NaN
1         NaN        NaN  계정과목 : [505] 상여금
2       차   변      대   변             잔   액
3    22638120        NaN          22638120
4    22638120        NaN               NaN
5    22638120        NaN               NaN
6    24899360        NaN          47537480
7    24899360        NaN               NaN
8    47537480        NaN               NaN
9    26460600        NaN          73998080
10   26460600        NaN               NaN
11   73998080        NaN               NaN
12   21813120        NaN          95811200
13        NaN   95811200               NaN
14   21813120   95811200               NaN
15   95811200   95811200               NaN
      Unnamed: 0                          Unnamed: 1 Unnamed: 2  \
0            NaN                                 NaN        NaN
1   회사명:(주)위너에코텍                                 NaN        NaN
2             날짜                         적    요    란         코드
3          01-31                             1월 사업소득        NaN
4          01-31  MATSUSHITA ￥150,000 * 1,077.62/100        NaN
5            NaN                     [ 월         계 ]        NaN
6            NaN                     [ 누         계 ]        NaN
7          02-28                             2월 사업소득        NaN
8          02-28  MATSUSHITA ￥150,000 * 1,036.15/100        NaN
9            NaN                     [ 월         계 ]        NaN
10           NaN                     [ 누         계 ]        NaN
11         03-31                             3월 사업소득        NaN
12         03-31  MATSUSHITA ￥150,000 * 1,030.12/100        NaN
13           NaN                     [ 월         계 ]        NaN
14           NaN                     [ 누         계 ]        NaN
15         04-30                             4월 사업소득        NaN
16         04-30  MATSUSHITA ￥150,000 * 1,032.50/100        NaN
17           NaN                     [ 월         계 ]        NaN
18           NaN                     [ 누         계 ]        NaN
19         05-31                             5월 사업소득        NaN
20         05-31  MATSUSHITA ￥150,000 * 1,014.31/100        NaN
21           NaN                     [ 월         계 ]        NaN

### 2018년

In [6]:
sheets = list(l_2018.keys())

#시트설정
for i in range(len(sheets)):
    sheet = l_2018[sheets[i]]
    
    year = 2018
    계정명 = sheet.iloc[계정명행,계정명열]
    계정명 = 계정명.replace("계정과목","")
    계정명 = 계정명.replace(":","")
    계정명 = 계정명.replace(" ","")
    
    #데이터프레임 추가
    for j in range(시작행,len(sheet)):
        if 월계 in sheet.loc[j].tolist() or 누계 in sheet.loc[j].tolist():
            pass
        else:
            row = sheet.loc[j].tolist()
            row.append(year)
            row.append(계정명)
            
            df.loc[len(df)] = row

### 2019

In [7]:
sheets = list(l_2019.keys())

#시트설정
for i in range(len(sheets)):
    sheet = l_2019[sheets[i]]
    
    year = 2019
    계정명 = sheet.iloc[계정명행,계정명열]
    계정명 = 계정명.replace("계정과목","")
    계정명 = 계정명.replace(":","")
    계정명 = 계정명.replace(" ","")
    
    #데이터프레임 추가
    for j in range(시작행,len(sheet)):
        if 월계 in sheet.loc[j].tolist() or 누계 in sheet.loc[j].tolist():
            pass
        else:
            row = sheet.loc[j].tolist()
            row.append(year)
            row.append(계정명)
            
            df.loc[len(df)] = row

KeyboardInterrupt:

### 2020

In [ ]:
sheets = list(l_2020.keys())

#시트설정
for i in range(len(sheets)):
    sheet = l_2020[sheets[i]]
    
    year = 2020
    계정명 = sheet.iloc[계정명행,계정명열]
    계정명 = 계정명.replace("계정과목","")
    계정명 = 계정명.replace(":","")
    계정명 = 계정명.replace(" ","")
    
    #데이터프레임 추가
    for j in range(시작행,len(sheet)):
        if 월계 in sheet.loc[j].tolist() or 누계 in sheet.loc[j].tolist():
            pass
        else:
            row = sheet.loc[j].tolist()
            row.append(year)
            row.append(계정명)
            
            df.loc[len(df)] = row

### 2021

In [ ]:
sheets = list(l_2021.keys())

#시트설정
for i in range(len(sheets)):
    sheet = l_2021[sheets[i]]
    
    year = 2021
    계정명 = sheet.iloc[계정명행,계정명열]
    계정명 = 계정명.replace("계정과목","")
    계정명 = 계정명.replace(":","")
    계정명 = 계정명.replace(" ","")
    
    #데이터프레임 추가
    for j in range(시작행,len(sheet)):
        if 월계 in sheet.loc[j].tolist() or 누계 in sheet.loc[j].tolist():
            pass
        else:
            row = sheet.loc[j].tolist()
            row.append(year)
            row.append(계정명)
            
            df.loc[len(df)] = row

In [ ]:
월 = []

for row in df['날짜']:
    월.append(float(str(row).split('-')[0]))

df['월'] = 월
df

In [ ]:
df.columns
col1= df.columns[-2:-1].to_list()
col2= df.columns[-3:-2].to_list()
col3= df.columns[-1:].to_list()
col4 = df.columns[:-3].to_list()
new_col= col1+col2+col3+col4
df = df[new_col]

In [ ]:
df

In [ ]:
file_name = input('Project명을 입력하세요: ')
file_name

In [ ]:
df.to_excel(file_name+'_원장.xlsx')